### ISSUE TITLE
Data Sources API: Flask REST framework with PostgreSQL

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#1]
# Background
We have a work-in-progress (WIP) repository, currently private, which makes a PostgreSQL mirror of the [Data Sources database](https://docs.pdap.io/activities/data-sources/what-is-a-data-source) using Airtable's API. Airtable's API is not suitable for building a front end, and long-term we're going to use Django and Postgres.

# Objective
The objective of this project is to host the PostgreSQL mirror on our Digital Ocean infrastructure and set up an API for internal development purposes. The API will provide access to the mirrored database and allow internal developers to interact with the data.

# Checkpoints
Use this project for reference on the status of the sub-tasks in this issue: https://github.com/orgs/Police-Data-Accessibility-Project/projects/21/views/1

**Comment by DouglasKrouth** [comment]
@josh-chamberlain @kalenluciano Is this still in the works and/or is there interest in doing this? Lot of background with Flask and Postgres, happy to work on this if it's a priority.
