### ISSUE TITLE
Link sharing issue

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-sources-app#129]
On dev, the quick search functionality is working in the data sources app, however navigating directly to a URL of search results is no longer functioning. I am unable to replicate this locally when building from the dev branch.

For example a 404 is displayed for this url: https://data-sources.pdap.dev/search/Calls/Chicago

**Comment by josh-chamberlain** [comment]
@mbodeantor we can call this closed, yes?

**Comment by mbodeantor** [comment]
yup!
