### ISSUE TITLE
troubleshoot local Data Source Details link

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#151]
### Context

[Discord thread](https://discord.com/channels/828274060034965575/1186730946561581178)

We held back Data Source Details from the [2023 app launch](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/83) because we couldn't get links from search results to load the detail pages—probably some kind of environment config issue. This was working while deployed, but not locally.

<img width="1512" alt="Screen Shot 2023-12-20 at 11 11 47 AM" src="https://github.com/Police-Data-Accessibility-Project/data-sources-app/assets/30379833/c2d8cd11-72bc-43b0-937a-5615ceda2bd1">

#### ↑ (local dev branch) http://localhost:5174/data-sources/rec09GnLmHWnRE3NJ

<img width="962" alt="Screen Shot 2023-12-20 at 11 12 56 AM" src="https://github.com/Police-Data-Accessibility-Project/data-sources-app/assets/30379833/1289f04c-d4ed-4d20-9abe-573842c91c0e">

### Issues

- [x] clicking "view source details" from the currently commented-out button on the `SearchResultCard` component should lead to a working source detail page. 
   - note: it will still be ugly if it works, because the styles haven't been touched since a bunch of custom styles were removed.
- [x] when I load sources directly, they have all null values: https://data-sources.pdap.io/data-sources/recPdBv9M0QhyKKZN

### Tests

- [ ] make sure this works on local and deployed branch before it goes to main

### Docs

- [x] if this is a local config issue, we should tell people how to set up their environment in the README

**Comment by josh-chamberlain** [comment]
@mbodeantor would you be able to look at this? the ability to link people to specific sources would be great.

**Comment by joshuagraber** [comment]
We'll need to merge #169 to `dev` just to make sure, but all other requirements have been confirmed.
