### ISSUE TITLE
Integrate es-lint config from `design-system`

### ISSUE THREAD

**Issue by joshuagraber** [Police-Data-Accessibility-Project/data-sources-app#165]
To establish consistency around linting rules, let's extend the config from `design-system`.

Blocked by https://github.com/Police-Data-Accessibility-Project/design-system/issues/40

**Comment by maxachis** [comment]
Since #40 is now resolved, I assume this is not blocked.

@joshuagraber Can you expand on what is meant by extending the config from `design-system` in this case?

**Comment by joshuagraber** [comment]
Hey @maxachis this issue is already finished, as part of a larger client linting and testing PR #195. Closing it out now.


> Can you expand on what is meant by extending the config from design-system in this case?

Sure. It's a combination of [adding the `eslint` config package](https://github.com/Police-Data-Accessibility-Project/data-sources-app/blob/fccf9336ebc11355e76bcda96bc09cac3c5d1602/client/package.json#L26) that we export from `design-system`, and [extending it in the `eslint` config file for `data-sources`.](https://github.com/Police-Data-Accessibility-Project/data-sources-app/blob/fccf9336ebc11355e76bcda96bc09cac3c5d1602/client/.eslintrc.json#L3-L5)
