### ISSUE TITLE
Data Source Search: results

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#17]
Requires Police-Data-Accessibility-Project/data-sources-app#15 

# High level
[Wireframe here (requires balsamiq desktop)](https://www.dropbox.com/s/2svk5lga9k6flu3/data%20sources%20search.bmpr?dl=0)

Display a filtered view of the Data Sources table as a grid of tiles, with a bit of information about the data source on each. With a bit of CSS, we can turn these same tiles into rows!

**Comment by mbodeantor** [comment]
@josh-chamberlain I believe this is done, lmk if there are changes you would like to the current grid display

**Comment by josh-chamberlain** [comment]
two changes from me:

1. clicking "source details" should take us to the Data Sources Detail view #18 for the selected Data Source, not show the "description" property. Let's just show the "description" by default.
2.

**Comment by kalenluciano** [comment]
I made these fixes on the [Data Source Detail static view task](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/18), so I'll link add that PR to this thread
