### ISSUE TITLE
Data Source Detail static view

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#18]
[Wireframe here (requires balsamiq desktop)](https://www.dropbox.com/s/2svk5lga9k6flu3/data%20sources%20search.bmpr?dl=0).

Shows properties in a sensible hierarchy / grouping. Permalink for each Data Source based on an ID of some kind.

**Comment by mbodeantor** [comment]
Looks like just a bit a tidying on this one. Found the text will sometimes run over into neighboring cards. Search for Complaints in Chicago:

![Image](https://github.com/Police-Data-Accessibility-Project/data-sources-app/assets/96697114/c86f0482-e90c-496d-bc52-54f066436b4d)

**Comment by josh-chamberlain** [comment]
I think there's some confusion, the screenshot attached covers #17 but "Data Source Detail" is meant to be a view which shows all the properties for a given Data Source.

<img width="905" alt="Screen Shot 2023-09-19 at 12 59 23 PM" src="https://github.com/Police-Data-Accessibility-Project/data-sources-app/assets/30379833/d9be4ba2-146b-4b78-8c4c-169f0525614a">

> The general idea is that we slap all the known properties about the Data Source on one page, grouped according to these 5 categories, plus a category for metadata about the Data Source itself.

> We may want to play with positioning and stuff when we see actual data in this view.

> These are grouped according to the data dictionary: https://docs.pdap.io/activities/data-sources/data-dictionaries/data-sources-data-dictionary

**Comment by mbodeantor** [comment]
Updated my comment
