### ISSUE TITLE
quick search: clarity and hierarchy, available record types

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#185]
### Context

Based on feedback from users of the search, we can make a few low-lift improvements to make the results more useful. Also one or two cosmetic things that aren't worth their own issue.

#### Quick search component
- [x] under the search button, add the text "For example, you could search for [stops in Pittsburgh](https://data-sources.pdap.io/search/stops/pittsburgh) or [complaints everywhere](https://data-sources.pdap.io/search/complaints/all)."
- [x] form labels should use `py-1` instead of `py-2` (as changed [here](https://github.com/Police-Data-Accessibility-Project/pdap.io/pull/168/commits/4fa6783ad040b61b61bf12beebd9ff19adb8d772#diff-16c7b4b48c978c7bab6fef0a40f6cc4ee19ac38355f999896072e88e4958e27fR35))

#### Search results
- [x] move the "Visit data source" button to just under the name of the source; leave the other button where it is
- [x] rename "View details" to "More details"
- [x] group results according to the parent groups for `record_type` [as designated here](https://docs.pdap.io/activities/data-dictionaries/record-types-taxonomy) (Police & public interactions, Info about officers, etc)
   - use h2s for the category titles
   - bonus: if it's easy to do, each of these could be a toggle menu (defaulting to open)
   - the wireframe below shows this, but is inaccurate re: the other things in this issue 
 
<img width="644" alt="Screen Shot 2024-01-17 at 2 06 31 PM" src="https://github.com/Police-Data-Accessibility-Project/data-sources-app/assets/30379833/fd374d11-d58c-4613-83ff-e6d40fd1978c">

**Comment by josh-chamberlain** [comment]
@joshuagraber once the dust settles from login, would you be able to knock this out? The other work we have planned for search can wait. Hopefully minor changes

**Comment by joshuagraber** [comment]
For sure @josh-chamberlain. All looks simple enough here, should be pretty quick. I'm working on tests to cover the login pages, then I'll move to this.
