### ISSUE TITLE
Data sources API endpoint

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#19]
This is a new endpoint which allows people to get data sources.

This is the default public endpoint, so it should automatically only show `approved = true (checked in airtable)` and `records_not_online = false (unchecked in airtable)` 

Don't include: https://docs.pdap.io/activities/data-sources/data-dictionaries/hidden-properties

**Comment by e-linear** [comment]
todo for self: fix so that this also returns the linked agency name (use quicksearch template)

**Comment by josh-chamberlain** [comment]
@e-linear I saw your comment so I decided to just make an issue: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/47
