### ISSUE TITLE
search bug: not showing results for health inspections

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#217]
This search returns 1 result: https://data-sources.pdap.io/search/health/allegheny

I think it should return 3. These are all `approval_status: approved` and have similar but not duplicate URLs. I'm wondering if they're getting rejected as duplicates, though?

<img width="678" alt="Screen Shot 2024-03-15 at 11 42 47 AM" src="https://github.com/Police-Data-Accessibility-Project/data-sources-app/assets/30379833/cf9d280f-89db-40ed-b41a-d42bb304053a">

**Comment by maxachis** [comment]
@josh-chamberlain I'd like to look at tackling this, although I think I'd need to familiarize myself a little better (and possibly document) how all the different components of the web application work together. It's not clear to me how to debug through the application.

@joshuagraber , at some point, would I be able to meet with you and debug through this issue to help me familiarize myself with the web app?

**Comment by joshuagraber** [comment]
Confirmed that this is an issue with the client @josh-chamberlain. API returns the following when I hit it from the command line:

<details>
<summary>API response</summary>
<code>
{
    "count": 3,
    "data": [
        {
            "agency_name": "Allegheny County Jail - PA",
            "agency_supplied": false,
            "airtable_uid": "recIiCBaZ4uUATKxP",
            "coverage_end": "2018-03-26",
            "coverage_start": "2018-02-23",
            "data_source_name": "Health Inspections for Allegheny County Jail 2/23/2018–3/26/2018",
            "description": "Inspections with date, purpose, and full report PDF. Allegheny County Jail is classified as a \"restaurant\" in this context.\nNote: there is more than one \"Allegheny County Jail\" entry in the database, so it's worth searching again if you can't seem to find the most recent one.\n",
            "municipality": null,
            "record_format": [
                "PDF: Machine Created"
            ],
            "record_type": "Contact Info & Agency Meta",
            "source_url": "https://eapps.alleghenycounty.us/restaurant/RestaurantDetail.aspx?ID=201408080003",
            "state_iso": "PA"
        },
        {
            "agency_name": "Allegheny County Jail - PA",
            "agency_supplied": false,
            "airtable_uid": "reczquCGZxYEgPSHA",
            "coverage_end": null,
            "coverage_start": "2021-02-23",
            "data_source_name": "Health Inspections for Allegheny County Jail 2/23/21–present",
            "description": "Inspections with date, purpose, and full report PDF. Allegheny County Jail is classified as a \"restaurant\" in this context.\n\nNote: there is more than one \"Allegheny County Jail\" entry in the database, so it's worth searching again if you can't seem to find the most recent one.\n",
            "municipality": null,
            "record_format": [
                "PDF: Machine Created"
            ],
            "record_type": "Contact Info & Agency Meta",
            "source_url": "https://eapps.alleghenycounty.us/restaurant/RestaurantDetail.aspx?ID=202102230002",
            "state_iso": "PA"
        },
        {
            "agency_name": "Allegheny County Jail - PA",
            "agency_supplied": false,
            "airtable_uid": "recgyWQl5fz6iMe80",
            "coverage_end": "2021-02-23",
            "coverage_start": "2018-07-25",
            "data_source_name": "Health Inspections for Allegheny County Jail 7/25/18–2/23/21",
            "description": "Inspections with date, purpose, and full report PDF. Allegheny County Jail is classified as a \"restaurant\" in this context.\n\nNote: there is more than one \"Allegheny County Jail\" entry in the database, so it's worth searching again if you can't seem to find the most recent one.\n",
            "municipality": null,
            "record_format": [
                "PDF: Machine Created"
            ],
            "record_type": "Contact Info & Agency Meta",
            "source_url": "https://eapps.alleghenycounty.us/restaurant/RestaurantDetail.aspx?ID=201808060005",
            "state_iso": "PA"
        }
    ]
}
</code>
</details>

@maxachis I've already diagnosed the issue (really an oversight on my part with a recent refactor of the search results). I'll raise a PR shortly and tag you in it, and if you'd like we can put some time on the calendar to discuss further and get to know the client app a bit better.
