### ISSUE TITLE
Cleanup old branches not in use

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#236]
Minor issue, but there are quite a few branches which appear to be inactive and are cluttering up the repo. Would benefit from some spring cleaning on these.

**Comment by EvilDrPurple** [comment]
I went ahead and cleaned up most of the branches, there were some older ones with significant unmerged changes I decided to keep for now in case we need whatever is in there

**Comment by josh-chamberlain** [comment]
thanks @EvilDrPurple ! I cleaned up a few more too
