### ISSUE TITLE
Github Action on Dev PR to Merge Dev into Main

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#238]
Derived from conversation [here](https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/233#issuecomment-2027374557).

Create a Github Action such that, on a Pull Request into Dev, automatically merge the latest version of Main into Dev.

**Comment by maxachis** [comment]
After meditating on a thousand mountaintops, I've concluded this isn't necessary, and may be detrimental. 🗻🧘‍♂️🏔️

Ideally, dev is always downstream of main. If the changes are minor, they'll be accounted for automatically in a merge. If not, then we probably want to make sure we're manually inspecting it in the merge. An automatic merge just increases the surface area where something could go wrong.

**Comment by josh-chamberlain** [comment]
I wish I had your gif't for reaction gifs. I bet there are a lot of good ones for the vivid imagery of mountaintops.

**Comment by maxachis** [comment]
![A majestic mountain](https://media1.tenor.com/m/t4PPp1jlWtwAAAAd/mountain-cat.gif)
