### ISSUE TITLE
add lat/lng to API

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#240]
### Context

related to 
- https://github.com/Police-Data-Accessibility-Project/data-source-map/issues/7
- https://github.com/Police-Data-Accessibility-Project/data-source-map/pull/6

### Requirements

- add the ability to get agency lat/lng from the API for mapping data sources and agencies
   - rather than adding to the existing data sources endpoint, we could add a new one. either way

**Comment by mbodeantor** [comment]
This should be a fairly straightforward change to the joins to the agency table in data_source_queries.py and any endpoint code downstream that selects columns from those queries.

**Comment by mbodeantor** [comment]
I think it should be fine to add this to current endpoints unless @joshuagraber you think that might break the client?

**Comment by joshuagraber** [comment]
> I think it should be fine to add this to current endpoints unless @joshuagraber you think that might break the client?

Not that I can see @mbodeantor. The only thing that makes a separate endpoint desirable from my perspective is related to performance. We could limit the endpoint to return only the data that we need for the map, which would speed the execution of the network call.

But doing that now may be premature optimization. Does it make sense to you to add this data to current endpoints for now then evaluate later whether performance would be improved by adding an extra endpoint?

**Comment by mbodeantor** [comment]
@joshuagraber No I think that's a good point, shouldn't be much more work to repurpose the current code for a new endpoint with only the fields the map needs. What would you expect those to be besides source_name, agency_name, lat, lng?

**Comment by joshuagraber** [comment]
Sounds good to me @mbodeantor. The above fields sound good, and I think I'll need `state_iso` and `municipality` as well. Won't be a big deal to add later if need be, but those should get me started.

**Comment by mbodeantor** [comment]
@joshuagraber PR here: https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/241
