### ISSUE TITLE
v2: search results

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#250]
part of #248 

see [wireframe](https://www.figma.com/design/UsbyOrgtBnLMyyqlfqIOqm/PDAP-Theming?node-id=4207-808&t=axBdWzOC8o64cX1C-0)

### Front end

- [x] replaces existing data source search results ([example](https://data-sources.pdap.io/search/segregated%20housing/allegheny%20county%20jail))
- [x] users can see currently open requests related to the search criteria
- [x] users can click a source to navigate to the details page
- [x] users can submit a new source
- [x] users can submit a new request
- [x] logged-in users can click a "Follow search" button to be notified about new sources and requests in the search
- [x] results are grouped by geographic area (in the wireframe as of 8/21), and the groups are collapsible (not in the wireframe)
  - #409 goes into more detail
- [ ] not in wireframe: give people the ability to sort search results by date added (default to most recent)

### API 

- [x] #256

### Cut from this issue

- #14 
   We can still show people their search terms in a simpler way, without showing all the options + scaffolds.
- #21 only becomes useful if people can make custom searches

**Comment by mbodeantor** [comment]
@josh-chamberlain Do users that save a search automatically "follow" it for new results or do we want separate functionality for that?

**Comment by josh-chamberlain** [comment]
@mbodeantor I adjusted the issue—`follow` and `save` are separate.

**Comment by josh-chamberlain** [comment]
consider: adding a non-intrusive "Did you find what you were looking for?" prompt with yes and no options. If "no", you could introduce the form to make a request, with the geography pre-filled from the search. there's a comments field on that form. 

If yes, maybe allow people to comment or just thank them for letting us know?
