### ISSUE TITLE
v2: data source details

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#253]
part of #248 

see [early wireframe](https://www.figma.com/file/XuGL7wistE2bE9hQ5ETUou/PDAP-Wireflow?type=design&node-id=4207-808&mode=design) and [theming wireframe](https://www.figma.com/design/UsbyOrgtBnLMyyqlfqIOqm/PDAP-Theming?node-id=4207-808&node-type=CANVAS&t=owimNEoWkNEPTZIS-0)

### Front end

replaces [example](https://data-sources.pdap.io/data-sources/recabQ04zvUH4RKQ0)
   - instead of being situated in a grid, the sections are accordions which can be collapsed
   - in addition to existing metadata, users can view related sources and requests involving the source
     - `related sources` are the same record type in different places; we can use existing endpoints
     - `related requests` are requests associated with the data source
   - let's use the `app/data-sources/{id}` route

### Back end

- https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/432

**Comment by mbodeantor** [comment]
@josh-chamberlain What logic do we want to use for determining which sources or requests or related?
