### ISSUE TITLE
v2: request details

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#254]
part of #248 

related to #251 

see [wireframe](https://www.figma.com/design/UsbyOrgtBnLMyyqlfqIOqm/PDAP-v2?node-id=6663-3622&node-type=canvas&t=YL0KfaPYsjM92cLB-0)

### Front end
   - a new view modeled after data source details
   - uses the `app/requests/{id}` route
   - we're not building a project management tool, so this is the summary plus relevant sources/agencies for a given request
   - links to a github issue for the request, where collaborators can comment
   - allow the person who created the request (and admins) to:
     - see and click a "Withdraw request" button and enter a `withdrawal_reason`
     - edit any of the fields they submitted on the form

### Back end

- [x] #256

**Comment by joshuagraber** [comment]
Hey @josh-chamberlain I'm unable to find the wireframe for this in the Figma files. Could you link me to it again?

**Comment by josh-chamberlain** [comment]
@joshuagraber sure, that's here: https://www.figma.com/design/UsbyOrgtBnLMyyqlfqIOqm/PDAP-v2?node-id=6735-5550&node-type=frame&t=pepP3MAwmcDVYbqw-0
