### ISSUE TITLE
v2: volunteer maintainer support

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#257]
now that users can log in, we need to give them permissions to sign up as a `maintainer` for a given geographic interest/search.

this allows us to notify them about requests relevant to their `maintainer` interests. 

- [ ] allow people to register as a `maintainer` for a search (or #22)
   - not sure what the entity relationship should be 
- [ ] allow people to link their GitHub account (maybe just username instead of full integration)
   - part of the user edit endpoint

**Comment by maxachis** [comment]
@josh-chamberlain This may follow #21, since presumably a search would need to be saved before someone can maintain it.

A few questions:
1. How do we connect a request to a community/search?
2. What happens when requesters make requests for data where we have no community or searches?

**Comment by josh-chamberlain** [comment]
Yep, this has to follow 21.

1. requests have geographic data, and often record types—so, we can surface them in searches for the same geography/record type.
2. this is assumed to be the case; by definition, we wouldn't be showing search results without, in the process, creating a search and therefore saving it. the request would be added to the database, and begin to appear in the relevant searches.
