### ISSUE TITLE
Map our data at county, state, federal level

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#27]
### Context

We want to use maps to:

1. visualize the work we want to do
2. track our progress
3. show close-up views 

First experiment: https://github.com/Police-Data-Accessibility-Project/data-source-map/issues/5

### Mapping requirements
- [ ] We should be able to display the API query and its results in some form near the map for troubleshooting and transparency; `See results in a table` or `Download CSV` or at least a link to the raw JSON
- [ ] Make sure we pick a mapping library that works well with our stack: Python, Vue, Tailwind
   - [ ] We need to be able to display 

U.S. map ([example](http://openelections.net/))
- Baseline: represent some metric about each state by making it a color; start with `quantity of data sources` or something dimple

State-level map
- [ ] Simple selector for state
- [ ] Like the U.S. map, but color each county

County-level map
- [ ] simple selector for state, county
- [ ] zoom in on the county
- [ ] put a dot for each agency on the map
- [ ] when an agency is clicked, show some basic data in a popup

### Docs

- [ ] A README.md file local to this project, or an entry in /docs
- [ ] A link to that README from the app

### Long-term ideas for representing our progress:

- Phase 1
  - We think we know about all the agencies in the county.
       - For the county/each municipality in the county, we have documented
          - police
          - courts
          - corrections
    - We can point to state-specific rules about police data publishing and access.
       - These can be in documentation or a database of legislation
       - Can we include Openstates for relevant legislature?
       _- Consider: any other helpful integrations to data sources_
- Phase 2: 
  - See [Agencies table](https://airtable.com/shr43ihbyM8DDkKx4/tblpnd3ei5SlibcCX)
     - For each of the known agencies from Phase 1, we should have all the required information.
  _- We need to improve our tools for tracking parent-child relationships and jurisdiction._
- Phase 3: 
  - We have combed each state for agencies with a recently-updated counties table.
  - For the most important `record_type`s, we either have a data source or a `records_not_online=TRUE` entry
  - We have contact info for records requests.
  - similar to [Vera's PDTI](https://policetransparency.vera.org/)
- Phase 4: 
   - We are publishing tools to normalize, combine, analyze, or otherwise work with local data in the state.
     - Phase 4 is never really "complete".

**Comment by maxachis** [comment]
@josh-chamberlain I feel like we've already done a lot of this -- is this still a valid issue?
