### ISSUE TITLE
v2 search logging

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#270]
### Context 
following https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/48

We should update our logging infra to make sure we're ready to handle searches (and maybe other activity). 

We don't want to track what named individual users are doing, and should actively _not_ do that.

This is for keeping track of what people search for and whether we show them results. It will will help us focus our data source ID efforts and front end in general

### Requirements

- [x] modify quick search logs ([PR here](https://github.com/Police-Data-Accessibility-Project/data-sources-app-v2/pull/3)) 
   - store the airtable_uid of data sources as results, not a full package
   - don't store `updated_at`
   - store a log, but not a `results` package, for quick searches of `all` and `all`, because they always return all results.
- [ ] set up log forwarding for searches
  - [ ] log a summary of the search parameters + a summary of the results
     - whichever format lends itself to flexibility (these formats may change over time) and searchability (elastic)
     - `query` could be key-value pairs for properties
     - `results` could be a list of sources by ID
         - this will help us track how many times a source appears in searches, an interesting metric for popularity
     - consider `response_time` or something to indicate performance, how long it took to get results back from the API / if we failed

**Comment by maxachis** [comment]
@josh-chamberlain Questions to ask in order to flesh this out further:

1. What data do we want to log? What searches are performed (e.g. how often a specific geographic location or record type is searched for)? What data sources are returned in a search? Other search parameters?
2. What do we intend to use the logged information for?
3. How long do we intend to retain the logged data? Indefinitely? Only for a specific period of time?
4. Who do we want to have access to the logged data? What roles/individuals?

**Comment by josh-chamberlain** [comment]
1. a summary of the search parameters + a summary of the results 
2. keeping track of _what people search for_ and _whether we show them results_ will help us focus our data source ID efforts and front end in general
3. indefinitely, until we run out of space and need to expire it
4. admins/staff/internal type people, unless random people want it (why, though) and it's safe to distribute

**Comment by maxachis** [comment]
@josh-chamberlain With that in mind, the `quick_search_query_log` part will require three distinct components, executed in the following order:
1. Modify the `quick_search_query_log` table in the database
2. Modifying the existing script(s) to change its behavior
3. Modify all _previous_ logs to enforce conformity with the new behavior

1 will involve modifying the [dev_scripts](https://github.com/Police-Data-Accessibility-Project/prod-to-dev-migration/blob/main/dev_scripts.sql) file in the prod-to-dev migration repository, so that after importing from prod to dev,  the new schema is applied.

3 will involve a one-time script, and we don't currently have a procedure for doing such actions. We could just say "yolo" and modify the database with a disposable query, but we may want to make sure any database changes we make are traceable, and that may require us to think a bit more about how to deploy one time scripts. And this will almost certainly not be the last OTS we deploy.

3 also adds an additional wrinkle in that we probably will want to apply this *after* the v2 changes are complete -- otherwise we'll have to deploy it after every dev database refresh to ensure it persists.

**Comment by maxachis** [comment]
> ### Context
> following #48
> 
> We should update our logging infra to make sure we're ready to handle searches (and maybe other activity).
> 
> We don't want to track what individual users are doing, and should actively _not_ do that.
> 
> This is for keeping track of what people search for and whether we show them results. It will will help us focus our data source ID efforts and front end in general
> 
> ### Requirements
> * [ ]  expand current logging direct-to-database, or formalize in elasticsearch or similar open-source logging package
> * [ ]  log a summary of the search parameters + a summary of the results
>   
>   * whichever format lends itself to flexibility (these formats may change over time) and searchability (elastic)

@josh-chamberlain Elasticsearch would probably be the best option, but we should note the costs. [Here](https://www.elastic.co/pricing) is the pricing for the ELK stack, with the lowest option being $95 per month. Trying to circumvent that through setting up a droplet wouldn't work, as the hardware requirements for the droplet(s) required for this would match if not eclipse the cloud pricing (to say nothing of having to learn how to set up all of that). 

That being said, for that price, we get a cloud-based solution with a lot of flexibility and [built-in analytics](https://www.elastic.co/elastic-stack). To use a technical term, that's pretty sweet. From what I know about our budget, I think we can handle this. Initially, it will probably feel like overkill, but it seems it will scale well.

**Comment by josh-chamberlain** [comment]
@maxachis Traceability for the old logs is nice, but not the greatest priority. The logs are just for us, so as long as they're usable at the end and we are confident they're accurate, they can be retroactively time stamped.

So, with that in mind: how about just creating a new table for logs and getting it working, then migrating the quick search logs once that's figured out? Who knows what may change in the meantime. As it stands, we still need to deprecate `quick search`, or modify it, but if it keeps loggin' away it will be the same amount of work to migrate it later.

re: cloud deployment, that's probably best! It almost never makes sense to accept the maintenance overhead for something we haven't tried yet.

**Comment by maxachis** [comment]
@josh-chamberlain Acknowledged! Will work on the design for a new `search_logs` table. 

> re: cloud deployment, that's probably best! It almost never makes sense to accept the maintenance overhead for something we haven't tried yet.

A little unclear if this means "We should look into Elastic" or "We shouldn't use Elastic without trying it". But in either case, Elastic does enable a 14 day trial where we could fiddle around with it and see how it looks.

**Comment by maxachis** [comment]
## Current Design: `search_logs`

* id, PK
* search_params, json array, NOT NULL
* search_results, json array or "ALL", NOT NULL
* result_count, int, NOT NULL
* created_at, datetime, NOT NULL

**Comment by maxachis** [comment]
@josh-chamberlain One thing also worth considering is implementing pagination for search results, both in the front-end display and back-end query. 

If our search results are currently returning upwards of hundreds of results in a single query, that's going to have issues in a number of domains, especially as our number of data sources grow:
1. As mentioned, logging all the results returned becomes cumbersome, even when we're only logging the IDs
2. Retrieving the data itself will become more resource-intensive over time.
3. If the point of logging is to identify the interests of our users, then returning a large amount of results will tell us very little -- we'll probably learn more about user interests not by how many results a search returns, but by when the user _stops_ searching -- i.e., indicating that they've found their desired results (or, more pessimistically, when they gave up searching).

With that in mind, we probably want to limit the number of results returned by a result -- at least initially. If we implement something like infinite scrolling, we can continually load additional data as the user looks for it. That would require adjustments to how we log data, but would help address the issues mentioned above. 

Finally, If we want logging information, it probably also benefits us to know what data sources are *clicked on*, in addition to merely retrieved. That can give us even more precise ideas of people's interest. That will require some additional efforts and logging adjustments, but could be powerful.

**Comment by maxachis** [comment]
@josh-chamberlain So if I'm understanding this correctly, The immediate agenda is the new `search_logs` table, with the design above. The two things outside the scope of v2 are ElasticSearch and Pagination.

**Comment by josh-chamberlain** [comment]
@mbodeantor do you have an opinion about whether we should expand on the simple search logs table, or move forward with elastic as discussed? 

I think either way pagination is separate—if someone gets results back, we should log all of them.

**Comment by mbodeantor** [comment]
Our needs for analytics seem pretty straight forward, would love to see what can do without elasticsearch first.

**Comment by josh-chamberlain** [comment]
@maxachis ↑

**Comment by josh-chamberlain** [comment]
Duplicate of #334
