### ISSUE TITLE
v2 Testing Overhaul

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#271]
With the suite of changes coming to v2, it would be valuable to develop a test environment which 
1.	More closely tracks the production database.
2.	Enables testing schema changes prior to implementing them in production.

In addition, current testing protocol could be revised and documentation added to ensure that testing is more easily understood by current and future contributors. 

The following is the set of proposals and sub-tasks required to implement this. 

## Set up test database

- [x] Set up test database on separate Digital Ocean Droplet.
- [x] Run scripts to refresh the schema (and possibly data) of the test database to those of the production database on a regular basis (once a week?).
- [x] Test all schema changes here before applying them to production.
- [ ] Set up a Github action to run all tests and scripts in the `dev` branch on a regular basis and/or as a precondition to pushing development code into production.
- [x] Determine if data should also be copied to test database from production, or if each test should populate and then remove its test data. 
- [ ] Set up documentation to ensure contributors are aware of the test database and how to interface with it.

## Revise current testing logic:

- [x] Replace test database referenced in `app_test.py` (created by `do_db_ddl_clean.sql`) with newly developed digital ocean test database. This will ensure tests properly emulate production environment and that the environment which tests run on is automatically updated to that production environment.
- [x] Build `tests` directory for running tests, and place all tests files (`app_test.py`, `app_test_data.py`, `regular_api_checks.py`) in this directory, for greater organization and to remove clutter in root directory.
- [x] Break up Tests into separate files for greater precision when running tests
- [ ] Add docstrings and additional documentation providing additional context when tests are run. 

## Desired Testing Organization:
per @josh-chamberlain 

name | purpose | testing | database
-- | -- | -- | --
app/main | live use | read-only tests for status checks | `prod-v1`
app/dev | "pre-prod" testing | db-affecting tests OK | sqlite (dev-v1)
app-v2/main | live use (secretly published) | read-only status checks | `prod-v2`, mirrored from `prod-v1` periodically*
app-v2/dev | "pre-v2-prod" testing | db-affecting tests OK | `dev-v2`, mirrored from `prod-v1` periodically

*If we have schema changes and migrations, we will need to make sure those run / stack on top of the v1 database over the course of v2 development.

type of testing | timing | purpose | db
-- | -- | -- | --
v1 automated status checks | async from code | "is the app running?" | `prod-v1`, read-only
v2 automated status checks | async from code | "is v2 running?" | `prod-v2`
`app/tests` | locally while coding, PR checks | prevent breaking changes | sqlite
`app-v2/tests` | locally while coding, PR checks | prevent breaking changes | `dev-v2` 

↑ I believe the local tests are the same ones which run on PR check, correct?

**Comment by maxachis** [comment]
@mbodeantor @josh-chamberlain I would like to have this be a precondition to finalizing any v2 API changes. With the sheer number of added endpoints and database changes, setting up a more structured testing system that better tracks with the production environment will go a long way towards ensuring our changes do not cause any undesirable side effects.

**Comment by josh-chamberlain** [comment]
adding this to the parent issue for v2

**Comment by maxachis** [comment]
@josh-chamberlain @mbodeantor I'll be setting up a separate DO database cluster for the dev database, rather than hosting another database on the same cluster. This means an additional monthly cost, but does mean we don't have to worry about resources competing, and reduces the risk of accidental interference with the production database. If you'd like it to be otherwise, let me know.

**Comment by josh-chamberlain** [comment]
@maxachis separate DO cluster sounds good.

my two cents about branches: In the past, we've had large projects going into `dev`, and enforcing `dev→main` makes it nearly impossible for anything else to get through while the large projects are testing. Adding a `check` like the other ones to raise a flag sounds OK, and best practice is dev→main, but I think we should still be able to merge straight into `main` if we find it necessary. 

If we just do a separate repo for v2 of the app, it gets easier to manage. I can't remember the issue now but it seemed Marty was on board with that as well.

**Comment by mbodeantor** [comment]
@josh-chamberlain Agreed, a forked repo would likely make things easier

**Comment by maxachis** [comment]
Oh yeah, that's a much more elegant idea, and I wish I'd thought of it. 

I don't have anything more productive to add at this moment. Just announcing idea FOMO.

**Comment by maxachis** [comment]
@josh-chamberlain @mbodeantor *NOW* I have something more productive to add! 

The dev droplet has been set up and populated with the necessary code and a cron job to copy the entire database from prod to dev every day at midnight. The process, currently, takes less than a minute. If we don't like this degree of frequency, we can easily modify it. 

I'm not going to check it off as done *quite* yet, because I need to make sure the cron job actually behaves as expected, come midnight.

**Comment by mbodeantor** [comment]
@maxachis While the cost is low, to minimize infrastructure maintenance this most likely would be able to share the droplet the Airtable mirror is running on without issue. I'll DM you the PEM

I also have that mirror set up to pull from Github, I think this is best for traceability, if you would replicate that for this script.

**Comment by maxachis** [comment]
@mbodeantor Sounds good. Will address later today and then remove the other droplet. May be useful to rename the data-source-mirror droplet to something else to acknowledge it's performing multiple functionalities.

**Comment by maxachis** [comment]
@mbodeantor @josh-chamberlain I was able to set up the directory in `data-source-mirror` and update the crontab (I didn't need the PEM, for whatever reason). I also renamed the droplet to `Database-Automation-Manager` to better encapsulate what it's doing, but that can easily be reversed if desired. Maybe at some point we'll want to combine these two repos into a single repo, just to simplify things further.

Next step will be setting up a means to import development schemas into the dev database. I considered the v2 repository, but that's already pretty crowded and would mean I'd have to do some additional wizardry and bring that into the Database Automation Manager (or DAM 🦫). So I'll probably update the prod-to-dev repository to also add in all development schema modifications after finishing the prod-to-dev dump.

**Comment by maxachis** [comment]
@josh-chamberlain @mbodeantor Next step will be setting up the configuration for the v2 app so that it points to the development database, which I think is something one of you will need to do as I do not know everything that goes into it or how to work with Digital Ocean to get that result.

We'll also need to figure out how to adjust the Github Action unit tests such that they point to the development database rather than the sqlite database, which I believe I should be able to help with.

**Comment by mbodeantor** [comment]
@maxachis I can add the other needed ENV variables and run command, but we will need the dev database url to finish the config

**Comment by maxachis** [comment]
@mbodeantor Just pm'd you the connection string! We may also want to create some specific DB roles at some point to further refine testing -- for the roles of developers, users, front-end, database maintainers, and the application itself. That may also be good practice to set up for the prod database. Don't think it's the highest priority at the moment, of course.

**Comment by mbodeantor** [comment]
Dev database url added as a variable in the data-sources-v2 app in DigitalOcean

**Comment by maxachis** [comment]
I've merged the latest changes in [this pull request](https://github.com/Police-Data-Accessibility-Project/data-sources-app-v2/pull/1). However, I'm still unable to get the Github action working properly, despite being able to get it operating correctly in [my test docker environment](https://github.com/maxachis/Python-Git-Docker-Test). I'm guessing it has something to do with the environment variables in Github Action, but that's just a guess. 

Considering that I'm currently the primary (only?) backend developer at the moment, I'll note this as something that needs to be completed for production, but which needn't obstruct development for the moment.

**Comment by josh-chamberlain** [comment]
@maxachis the github action is a nice failsafe, but we should only merge code that passes the tests so I'm down to remove this as a requirement. I made a new issue for docs, so we can close this one. Nice work! 

https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/297
