### ISSUE TITLE
quick_search_query_logs table stores extremely large amounts of information.

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#279]
As a refresher, the `quick_search_query_logs` table stores the query logs of quick search. It currently records, among other things, the `search` and `location` parameters used (in columns of the same name), as well as a json array of all the data source results in the `results`column.

These logs, particularly when both the `search` and `location` parameters are blank, store a lot of data in the `results` column. In the case where `search` and `location` are blank (currently 372 out of 4752 entries), effectively all valid results are returned and logged in the `results` column. More recently, this means that every search with all-blank parameters stores over 900,000 characters in the `results` column. In December, this was over 1 million characters per search. Around 10% of queries currently recorded in the database return over 100 results, which places a sizeable amount of characters in the `results` column.

This is already causing problems in the database – viewing the data alone is quite difficult just because of the sheer size of the column. Performing a select statement to retrieve the data takes an intolerably long time unless I limit the number of queries returned, and even that is long. 

This will become more of a problem as time goes on and the application becomes more widely used. The storage costs for this column alone outsize significant portions of the rest of the database, and the storing and processing of such large amounts of data rack up memory and CPU resources. Timeout and errors could occur on the user end if users perform actions that cause the application to try to query or update such a large dataset. 

This needs to be addressed, and preferably sooner rather than later.

# Solutions
The solution preferred will depend on how precisely we want to store a record of the queries returned. 

1. One simple solution would be to replace the entire suite of results with just the primary key of each result, i.e. the airtable_uid. This would automatically reduce the size of each result to 5% of its original size while retaining most information – the only thing lost is the snapshot of the properties of each result at that moment, which are unlikely to change substantially over time. 
2. A long-term solution, which has been discussed previously, would involve using a document store or NoSQL database if we absolutely must store these large JSON objects as is. 
3. We may want to archive query data regularly – these logs are not essential to the day-to-day operations of the application, so regularly pruning these logs and moving them elsewhere is likely to be useful.
4. We may want to decide to modify how we handle the retrieval and logging of searches where all parameters are blank, meaning that all valid data entries are returned. Especially if the database hasn’t been updated, or the same search query is entered multiple times, we’re just duplicating efforts if we gather all these results on every request. Consider caching frequent searches, preventing users from making searches that return the entire database, or implementing pagination that return only a subset of these results at a time. 
5. Other possible solutions abound, depending on the intended utility of these query logs and our imagination 🌈

**Comment by maxachis** [comment]
@josh-chamberlain @mbodeantor Tagging y'all directly in this case as I think this should be addressed as part of #248. Wider usage of the app will cause this problem to grow in scope considerably. How we address this also informs how we address future logging of searches.

**Comment by maxachis** [comment]
Also as a minor issue, I'm not sure what the functionality for the different `created_at` and `updated_at` columns are -- the vast majority of these queries have the two within a second of each other, with only a handful diverging by more than a minute.

**Comment by josh-chamberlain** [comment]
@maxachis 

1. replacing the results with the primary keys sounds fine to me.
2. if someone searches "all" and "all" we shouldn't store the results; we know they got everything back. We should still log that they made the query, but replacing the results with something smaller and more sensible that indicates "everything" would be OK. 
3. `updated_at` might be there because of `saved searches` in the future, but it doesn't need to be there now.

what do you say we resolve this in #270 ?

**Comment by maxachis** [comment]
@josh-chamberlain Sounds good to me! I will consider this issue closed in favor of #270.
