### ISSUE TITLE
Remove manual insertion of datetime, add triggers to `quick_search_query_logs`

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#290]
Currently code in the `quick_search_query()` function in `quick_search_query` inserts a datetime entry into the `quick_search_query_logs` column:

```python
  current_datetime = datetime.datetime.now()
  datetime_string = current_datetime.strftime("%Y-%m-%d %H:%M:%S")

  query_results = json.dumps(data_sources["data"]).replace("'", "")

  cursor.execute(
      INSERT_LOG_QUERY.format(
          search, location, query_results, data_sources["count"], datetime_string
      ),
  )
```

We can replace this with a database trigger. This will reduce our Python code and reduce the risk of timezone difference issues (currently the datetime of the timezone being inserted is four hours ahead of the timezone recorded in the database).

**Comment by maxachis** [comment]
@josh-chamberlain We may have a redundant column. Here is the creation script for the `quick_search_query_logs` table:

```SQL
CREATE TABLE IF NOT EXISTS public.quick_search_query_logs
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    search character varying COLLATE pg_catalog."default",
    location character varying COLLATE pg_catalog."default",
    result_count bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    datetime_of_request timestamp with time zone,
    results jsonb,
    CONSTRAINT quick_search_query_logs_pkey PRIMARY KEY (id)
)
```

It doesn't seem to be the case that `datetime_of_request` has a different functionality than `created_at` -- should it be removed?

**Comment by josh-chamberlain** [comment]
@maxachis true, that's redundant.

What do you mean by `database trigger`? Do you mean like `GETDATE()` in SQL?

**Comment by maxachis** [comment]
> ```sql
> created_at timestamp with time zone NOT NULL DEFAULT now(),
> ```

@josh-chamberlain At the time, I meant a trigger where, on insert, the datetime would be inserted into the relevant column.

However, if `created_at` and `datetime_of_request` are redundant, I can simply get rid of `datetime_of_request` and, as long as my insert doesn't touch `created_at`, a datetime will be added there at time of insertion.
