### ISSUE TITLE
Add tests at API level for SQL injection

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#291]
Our API calls are the point at which untrusted data enters the system. Thus, it's essential to ensure that no API calls are vulnerable to SQL injection. 

Tests should be added for every API call to ensure that obvious SQL injection attacks cannot occur.

**Comment by maxachis** [comment]
This might be a good tool for automated penetration testing

https://github.com/sqlmapproject/sqlmap

**Comment by maxachis** [comment]
I went ahead and ran SQLMap against what would probably be the easiest one to SQL Injection test -- `/typeahead/agencies`. 

I say easiest because this is the endpoint that does not require any kind of authorization, and which is quite generous in terms of rate limiting. 

No vulnerabilities were detected. A full list of the tests run can be found here, for those interested:

[results.txt](https://github.com/user-attachments/files/17959590/results.txt)

Now, use of SQLMap does not yield any vulnerabilities from this one endpoint. Our [Bandit](https://github.com/PyCQA/bandit) scans do not detect SQL injection vulnerability. 

Now, six months ago, I said:

> Tests should be added for every API call to ensure that obvious SQL injection attacks cannot occur.

And I'm not sure I agree anymore. I could see some potential value in developing a means of performing automated testing with SQLMap, or expanding testing to additional endpoints, but considering the results from `Bandit`, and the results from this as a sanity check, it may not be the best use of our limited time and resources. 

@josh-chamberlain What do you think?

**Comment by josh-chamberlain** [comment]
@maxachis yes, I'm thinking we are taking general steps to prevent SQL injection which _should_ make testing each endpoint redundant. We're using SQLAlchemy, permissions, constraints...I think we're good!

**Comment by maxachis** [comment]
@josh-chamberlain Alright! I'll consider this one closed!
