### ISSUE TITLE
add timeout to requests calls

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#298]
https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/260

> I'd probably want to make it so that we're calling a singular function which makes the request with the necessary parameters rather than having to put the same argument in every call to `requests.get()`.

**Comment by maxachis** [comment]
Rather than creating a custom function for this, we could probably use the [httpx](https://www.python-httpx.org/advanced/timeouts/) library, which includes timeouts by default. [Here's](https://oxylabs.io/blog/httpx-vs-requests-vs-aiohttp) an overview of how it compares to `requests`.
