### ISSUE TITLE
Resolve Test App Setup Issues

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#301]
Using the main README file in the repository, I've attempted to start up the test version of the app and access it via a web application, just to do exploratory testing and as a sanity check to make sure my code isn't cataclysmically breaking anything.

However, even when using the `main` branch in the primary `data-sources-app` repository, I'm not able to run the app successfully, for reasons that are unclear to me. If I attempt to perform searches, for example, I'm unable to pull any results, and checking the browser console log, errors are being reported. It's unclear if the REST methods are even being called successfully.

Again, this is the `main` branch in the main repository, so none of my code should be affecting it. I am using the dev database, but I should still at least be able to access the REST methods and receive the custom error methods from them, but I am not. 

I'd like to work with whomever is most in the know about how to use this portion of the application and figure out how to diagnose this problem. If the problem has to do with information not included in the documentation, I'd like to add that to the README for v2.

**Comment by josh-chamberlain** [comment]
most in-the-know is probably @joshuagraber. This is my fault, I should have made sure we had a better process for getting new devs' local envs set up! I should probably be involved in this effort to capture it for next time..

**Comment by maxachis** [comment]
This has been resolved! Issue closed!
