### ISSUE TITLE
Add default role to `users` table and make roles enum

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#316]
Currently, in the `users` table in the database, roles are either "admin" or `null`. This forces the middleware logic to make assumptions as to what kind of role a user has, typically defaulting to "user". When adding users, we should probably make sure their role is set to a default value of "user", rather than `null`. 

Additionally, we may want to ensure the roles are limited only to a set of enums. Currently, the only enums would be "admin", "user", but this could conceivably expand in the future.

**Comment by maxachis** [comment]
Create a dev script update to this, but will need to complement with a web app update which is to be merged at the same time.

**Comment by josh-chamberlain** [comment]
I think we'd deprecate the `roles` concept when we close #162—though maybe not.

**Comment by maxachis** [comment]
Josh is right! This issue can thus be closed.
