### ISSUE TITLE
v2: remove search tokens

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#322]
### Context

Part of https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/318

We are using search tokens to hide the public auth token from the client; this has been determined to be overkill, and I'm dropping it as a requirement for v2.

We'll use #353 to protect us from spam.

### Requirements

- [ ] This means `search tokens` are probably unnecessary; we should drop them from the code and docs 
  - we will implement JWT for `admin` endpoints
- [ ] the client (and any additional clients we make using our API) should still use its own API key
- [ ] Alert front end devs of the changes; we will take advantage of these changes in v2

**Comment by maxachis** [comment]
@josh-chamberlain It'll be very simple for me to remove search tokens and the associated testing code, but my main question is: what is currently calling this, and where will that be redirected?

**Comment by josh-chamberlain** [comment]
@maxachis currently, it seems to me the only time these are used is for current quick search from our front page.

Since we'll have a new search endpoint (#249), we don't have to use search tokens. 

However, note the following line from that issue:

> - if there are no typeahead results: the option should be `No results found. Search for "string"?` and load quick search results

So, in an edge case, we'll still use the quick search endpoint...but it need not use search tokens. We can eliminate that edge if the scope is creeping too much.

**Comment by maxachis** [comment]
@josh-chamberlain In that case, would that mean that removing search tokens is contingent on that new search endpoint being introduced?

**Comment by josh-chamberlain** [comment]
@maxachis I brought up the search endpoint to say search tokens aren't needed; we don't have to wait, though.

**Comment by maxachis** [comment]
@josh-chamberlain Got it!

@joshuagraber I can remove the SearchTokens resource and endpoint right away, but we'll get errors thrown in the web app until the endpoints on the frontend are redirected. Are you able to do that?

**Comment by josh-chamberlain** [comment]
@joshuagraber @maxachis Yes, just for `v2`. It's OK (I think) to make changes that break the v2 dev app, which will need to happen for some changes in the API. Like omelets

**Comment by maxachis** [comment]
@josh-chamberlain @joshuagraber I've created pull requests to remove the `search_tokens` table and attendant logic. This means that the search functionality, which relies on the `/search-tokens` endpoint, is currently broken. Frontend changes should be as simple as redirecting these calls to the true endpoints. 

My recommendation is that, before we consider this issue closed, we address that as well, so that searches can still be done in the v2-dev app.

**Comment by maxachis** [comment]
Additionally, I modified the `/login`. Whereas previously a session token was returned, now a "DUMMY_TOKEN" value is returned in the same position. This was done to prevent additional breakage, but obviously this will need modified once we reconfigure login logic through #372 or other solutions.

**Comment by joshuagraber** [comment]
@maxachis Instead of deleting endpoints, could we follow [API sunsetting best practices](https://nordicapis.com/how-to-smartly-sunset-and-deprecate-apis/) instead? This would make migration from clients (ours as well as anyone else who might be using the APIs) a lot easier.

> Additionally, I modified the /login endpoint logic somewhat. Whereas previously a session token was returned, now a "DUMMY_TOKEN" value is returned in the same position. 

Can you explain more why we're doing this? And what "breakage" it's meant to prevent? From my perspective, this will cause breakage rather than preventing it. Logging in _should_ return a bearer token that allows the user to access protected endpoints to which they are entitled. If not, how else is the client supposed to retrieve this information?

**Comment by maxachis** [comment]
> @maxachis Instead of deleting endpoints, could we follow [API sunsetting best practices](https://nordicapis.com/how-to-smartly-sunset-and-deprecate-apis/) instead? This would make migration from clients (ours as well as anyone else who might be using the APIs) a lot easier.
> 
> > Additionally, I modified the /login endpoint logic somewhat. Whereas previously a session token was returned, now a "DUMMY_TOKEN" value is returned in the same position.
> 
> Can you explain more why we're doing this? And what "breakage" it's meant to prevent? From my perspective, this will cause breakage rather than preventing it. Logging in _should_ return a bearer token that allows the user to access protected endpoints to which they are entitled. If not, how else is the client supposed to retrieve this information?

My rationale at the time of doing this (which seemed like a good idea at the time 🙃) was simply to prevent an error where the client would be pulling data using a key-value pair that doesn't exist. 

In retrospect, I do see why this would cause more issues. And considering that we're still debating auth, these methods were premature anyway.

**Comment by josh-chamberlain** [comment]
@joshuagraber FWIW, we're the only users of our API at the moment—more specifically, _you_ are. That may not change the best practices around sunsetting
