### ISSUE TITLE
deprecate `regular_api_checks.py`

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#323]
### Context
We used to have a github action that periodically ran to check the API for basic functionality. Now, we have the [health monitoring repo](https://github.com/Police-Data-Accessibility-Project/health-monitoring/).

These tests were related to Police-Data-Accessibility-Project/data-sources-app#154

### Requirements

- [x] remove the `VUE_APP_PDAP_API_KEY` and `VUE_APP_PDAP_TOKEN` variables at the org level
- [x] remove files dependent on `VUE_APP_PDAP_API_KEY` variable
   - regular_api_checks.py
   - outdated tests files 
   - none of these files should be working, because the variable has long been defunct
- [x] remove github actions triggering these files/tests
   - if any bits of the tests _do_ seem to be working, we can discuss further

**Comment by josh-chamberlain** [comment]
@maxachis your [work in health monitoring](https://github.com/Police-Data-Accessibility-Project/health-monitoring/blob/main/scripts/check_search_endpoint.py) looks great. I think we're about ready to set up your script to run on a cron job w/ github action, would you agree?

**Comment by maxachis** [comment]
Prior to eliminating `regular_api_check.py`, we may want to consider migrating some of these checks to the Health Monitoring repo.

However, we may not want to include all of these tests, for a few reasons:
1. Many/all of these test functionality already tested in the newly added integration and unit tests that run in the dev environment -- unless we've reasons to believe prod will differ substantially from dev, running these again would be redundant. 
2. Some of these tests are POST or PUT requests, which would modify the production database when run -- not something that should be done without careful consideration. 
3. Some carry specific "test flags", which have been deprecated from the code, so these would need to be modified in turn. 
4. Granular testing of production may give us less bang for our limited buck than more generalized, non-intrusive tests which target common points of failure -- any endpoint responding will help us validate that endpoints in general are not down; checking that the server and client are online and responding to basic PINGs or ping-equivalents is also important; checking metrics such as latency of response, CPU/RAM/storage load of servers, 

I'll work on creating an issue advocating for what to include in health monitoring.

**Comment by EvilDrPurple** [comment]
@josh-chamberlain @maxachis I went ahead and completed the outlined changes in the linked branch. I can hold off on submitting the PR if you wanted to evaluate if there are any checks worth saving before moving forward

**Comment by maxachis** [comment]
> @josh-chamberlain @maxachis I went ahead and completed the outlined changes in the linked branch. I can hold off on submitting the PR if you wanted to evaluate if there are any checks worth saving before moving forward

@EvilDrPurple From my vantage point, you can go ahead and submit: After reviewing, I only saw one that might need re-adding, and only as an integration test, not as a health check: I've noted that in #329

**Comment by josh-chamberlain** [comment]
Saving the pagination check is good, but I figured since this wasn't working anyway it'd be better to deprecate and move to the new tests. Thanks y'all! @EvilDrPurple you could feel free to look at #329 if you want to work on tests in the new infrastructure.
