### ISSUE TITLE
Setup Documentation for Automation Manager Droplet

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#324]
The Automation Manager is the latest name for a Digital Ocean Droplet which currently hosts the following repositories:

- https://github.com/Police-Data-Accessibility-Project/health-monitoring
- https://github.com/Police-Data-Accessibility-Project/data-sources-mirror
- https://github.com/Police-Data-Accessibility-Project/prod-to-dev-migration

Most of the knowledge of how this works exists in my head, which is a dangerous place and also poses the systemic risk of me dropping it in the toilet or something and no one else knowing how this stuff comes together. So documentation needs to be developed and integrated into our overall documentation.

This will probably involve two components: 
1. Information in our Gitbook about the Automation Manager in general
2. Information in each of the respective Readmes about how they work _within_ the automation manager. Where it is deployed, how often it is triggered, how to verify it is functioning as expected or when it last ran, and so on.

**Comment by josh-chamberlain** [comment]
@maxachis thanks—this could be exceedingly simple, just so we have enough breadcrumbs to find the trail!

**Comment by maxachis** [comment]
@josh-chamberlain I created a [Gitbook pull request ](https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/499/activities/backend/digital-ocean)for changes to the Gitbook documentation, referencing Digital Ocean, Droplets, and specifically the Automation Manager droplet. I know you said that I could just merge documentation and reference the merge request, but in this case I'd like a sanity check from you to make sure this is the type of information we want in the Gitbook, and if it's not redundant with anything else.

**Comment by josh-chamberlain** [comment]
@maxachis thanks for writing this and running it by! I actually just copied it into the developer resources notion page, digital ocean → droplets. https://www.notion.so/pdap/Digital-Ocean-Hosting-6ca5f9ef9aa04a81a59b080ef55e2233?pvs=4

I think of those notion docs as "internal", for people who need to manage infra. The public docs are more for people who are _using_ PDAP as a service, if that makes sense. I think we could close the gitbook PR now, while still closing this issue! Thank you for that.
