### ISSUE TITLE
Set up manual test checklist to confirm basic functionality

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#326]
In addition to developing automated integration, unit, and end-to-end tests, we should also have a checklist of manual tests to perform prior to moving a large suite of changes from dev to production. This is a sanity test designed to make sure that tests and other metrics aren't missing anything obvious prior to release.

Such a checklist should cover the most critical elements of app functionality. At the same time, we should probably not make them so extensive as to make it a substantial burden to perform -- these are meant to be sanity tests, not duplications of our automated testing efforts. We should figure out how long it should take to perform the manual tests (10 minutes, perhaps?), and then design the tests to be done within that timeframe.

We should also encourage more meandering exploratory testing prior to release, where in addition to the essentials covered in such a checklist, the developer plays around and sees if things perform as expected, and record anything unexpected. Maybe deliberately try to break the app and see if they are successful.

These tests should be both a prerequisite to deploying to production and a check after deployment -- it is always possible that migrating between the two environments causes unexpected issues. 

Such a Checklist should be included in the Gitbook.

**Comment by maxachis** [comment]
Candidates for manual tests include:

- Do all critical pages load as expected? Can I navigate to these pages from the home page?
- In the console of the page (accessible through Chrome developer mode), do any errors pop up when performing standard actions?
- Can I search for a known agency and pull results?
- Otherr?

**Comment by maxachis** [comment]
@josh-chamberlain I've created Gitbooks PR for a Release Sanity Checklist. This is another Gitbooks PR where I'd like to have your eyes on it to confirm it's appropriate and whether I'm missing anything relevant:

https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/500/dev-guidelines/testing/release-sanity-checklist

**Comment by joshuagraber** [comment]
@maxachis this looks like a pretty good list. A couple of comments / notes:

> Do all of these also function as expected from a mobile interface (even if just one simulated in Chrome Developer view or elsewhere?)

To be really comprehensive here, we would want to do this on `dev` with actual mobile devices or the `xCode` or `AndroidStudio` simulators. The browser simulators are not 1-1 with actual device behavior.

> Performance: Do pages and actions resolve quickly?

How do we define "quickly"? And how are we measuring? Just an eyeball test, and if it "feels slow" we look into it? Or do we want to use an actual performance dev tool?

> Any other key user workflows (including some we will add in v2)

Logging in, for one thing. There are flows for changing and resetting passwords as well. Maybe we create and update a list of flows to check?  

  
--

And one thing I think is missing from the above: accessibility. We should navigate the app with a screen reader at random and/or use a11y-focused dev tools. 

I've been meaning to add [this](https://www.npmjs.com/package/eslint-plugin-vuejs-accessibility) to our linting config in `design-system` (which will then automatically extend to `data-sources-v2`), which will help catch issues before they go to production. But these tools aren't perfect, and manual testing is essential for accessibility stuff.

**Comment by maxachis** [comment]
@joshuagraber @josh-chamberlain 

I like all of these ideas, and think we should implement all of them. 

The main question is how many do we apply on the sanity checklist? The more steps we add, and the longer it takes, the more someone in the future is likely to skip steps. Ideally (in my opinion, anyway), the checklist should be Friday afternoon proof -- if it's the last thing you do on a Friday afternoon before the weekend, you don't get tempted to cut corners just to get to Margaritaville faster.

The more we use tech unfamiliar to people, like a screen reader or mobile simulator if they're not used to that, the more that risk increases. And for things like a screen reader, only a subset of the audience will use that, whereas we expect the home page and search feature to be something all users will use.

We may want to consider additional checklists for larger releases, where a more comprehensive set of checks is warranted and the people pushing them through are more motivated/paranoid to ensure nothing's broken. But in the case of hotfixes or small but rapid iterations, we're fighting against the patience of whoever's behind the wheel who wants to think everything's fine because they want to just push it through.

> How do we define "quickly"? And how are we measuring? Just an eyeball test, and if it "feels slow" we look into it? Or do we want to use an actual performance dev tool?

I think "feels slow". We can use automated metrics for performance evaluations, but the sanity check should be more of a quick smell test. There's an element of subjective variability in that, but it also is quick and generally reliable. 

Additionally, for our v2 dev releases, we need to also set up the v2 dev and prod versions of the web app, so someone can actually access them from a phone or something similar. I don't believe we've made an issue for that yet.

**Comment by joshuagraber** [comment]
> But in the case of hotfixes or small but rapid iterations, we're fighting against the patience of whoever's behind the wheel who wants to think everything's fine because they want to just push it through.

Well, yes, exactly. A proper manual testing regime requires people dedicated to that work, and we don't have that capacity.


> The more we use tech unfamiliar to people, like a screen reader or mobile simulator if they're not used to that, the more that risk increases. And for things like a screen reader, only a subset of the audience will use that, whereas we expect the home page and search feature to be something all users will use.

Sure, I see your point here. And agree about the mobile sims, probably not necessary unless we're fixing a mobile-specific bug... 

BUT I'd be remiss if I didn't challenge your point on the screen reader stuff. Accessibility is incredibly important. The idea that a screen reader could be considered "unfamiliar tech" to people working on user interfaces is asinine at this point. These are things that front end engineers (good ones, anyways) are familiar with and do consider when building things. It's a part of the job. 

The "subset of the audience" argument is often used to ignore accessibility work and testing, but that doesn't make it a good argument. From my perspective, it's a moral responsibility to ensure our apps are accessible to everyone—not to mention there is significant legal risk if we don't (organizations are regularly sued over this stuff, and for pretty "minor" things).

> The main question is how many do we apply on the sanity checklist? 

But you're right, it can't be too long. What about this idea? We create a "master manual testing checklist" that includes all of the things. Then we create a PR template that includes a section "Manual Acceptance Criteria" or something like this, and the PR owner is responsible for picking and choosing from the "master checklist" which items are germane to their PR and including in that section of the PR template. That could make it both exhaustive and flexible.

> Additionally, for our v2 dev releases, we need to also set up the v2 dev and prod versions of the web app, so someone can actually access them from a phone or something similar. I don't believe we've made an issue for that yet.

Sure, that's just cloning the prod release config and swapping dev-specific env, right? Relatively trivial.

**Comment by josh-chamberlain** [comment]
@maxachis @joshuagraber thanks for thinking on this. I approved the gitbook PR with slight modifications, as it's a good starting point—we can all make changes to the QA checklist to improve it over time. Mostly, I just changed the name to "Production QA checklist".

1. I can take on the QA responsibility, as I have done historically. When there's a big PR to update `main` from `dev`, I basically run through this checklist already—now there'll be a more formal process, which is good.

2. as for deploying `v2-dev` and `v2-prod`, that can happen whenever. will DM about it

**Comment by maxachis** [comment]
@josh-chamberlain With https://data-sources-v2.pdap.dev/ now up, we have an opportunity to put things into place to push dev into main. Once dev is push into main, we can then fix `v2-prod` and set it up. We can also close the many issues currently marked as `in-dev`. Unclear if that should be discussed in this issue or in a separate issue.

**Comment by josh-chamberlain** [comment]
@maxachis yes, it's a good time to do that, I think! The best place to discuss it is probably on a big `dev → main` PR, which fixes many issues at once. In the past, I created those big issues. However, I feel a little weird making a PR that represents almost exclusively work by other people. Plus, then you would be approving it, when I think it should be the other way around.

I think it will also close this related issue: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/333

**Comment by maxachis** [comment]
Now that these have been set up, we can close this issue! Hooray! 🐘
