### ISSUE TITLE
Publish most-used / useful extractions for public download

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#33]
We're not yet sure what these will look like, but we assume that one day we will have a bunch of Extractions that are so commonly used it makes sense to host them somewhere browser-accessible.

**Comment by maxachis** [comment]
@josh-chamberlain I'm going through some old requests -- is this still relevant?

**Comment by josh-chamberlain** [comment]
@maxachis not really, no.
