### ISSUE TITLE
Set up data-sources-v2-dev and data-sources-v2 Digital Ocean Apps

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#333]
Now that we're ready to start doing more flexible testing, it's time to start setting up these applications.

Currently, `data-sources-v2` exists in Digital Ocean, but its build has been failing. I think I know why, but to make sure I'm right, I'll need to get `data-sources-v2-dev` started first and be able to implement steps that `data-sources-v2` will emulate.

I can probably do a lot of the requisite steps on my own, but things that I probably _can't_ do on my own is:

- [x] Create the initial version of `data-sources-v2-dev` and connect that to the proper Github Repository and Branch (I tried, and GitHub said that I need to be the organization owner). @josh-chamberlain I think this means you'll need to step in here.

**Comment by josh-chamberlain** [comment]
@maxachis `data-sources-v2-dev` created. I used the dev database envar and didn't add a secret key yet since I'm not sure whether we need a separate API key for dev stuff.

**Comment by maxachis** [comment]
@josh-chamberlain Excellent. Working on setting it up now. I am wondering if we want to give the app admin-level permissions to the dev database -- it's dev, so it's not the most risky thing, but we probably want to develop a precise role that is more specific, if we don't have that yet (and I think we do).

**Comment by maxachis** [comment]
@josh-chamberlain It's up! 

https://data-sources-v2.pdap.dev/

**Comment by josh-chamberlain** [comment]
@maxachis woohoo! that's great.

re: admin-level permissions, sounds good—I think we should discuss it. We do plan to give people described as "admins" the ability to edit requests here: #256 

we don't have too many other admin actions planned yet. we would probably use `retool` or something, with dedicated endpoints, for internal tools (or develop internal tools as their own little app)

so, now's a good time to get more precise.

**Comment by maxachis** [comment]
Now that everything here seems to be properly set up, I think we can comfortably close this issue.
