### ISSUE TITLE
API key security and recoverability

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#335]
### Context

> Having a permanent API key be unencrypted in the database is probably a security hole.

### Requirements

- We should store a hashed version of API keys in the database. 
- We should also have a way, using secrets kept in `keybase`, to regenerate an admin API key in the future. We should then document that process in notion dev docs.
- We should have an API key for the client to use; it may have different rate limiting considerations
  - #353

**Comment by maxachis** [comment]
This is related to #162 , in that depending on what direction we go in with the permission structure, API keys might be modified or obviated.

**Comment by josh-chamberlain** [comment]
Confirmed non-obviation!

**Comment by josh-chamberlain** [comment]
duplicate of https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/388
