### ISSUE TITLE
v1 bug: "view data source" link malformed

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#338]
## Steps to reproduce

Make a search, like: https://data-sources.pdap.io/search/calls/all

The first source is "Calls for Service for Los Angeles Police Department - CA". If you click "view source", or source details then the URL, it takes you to https://data-sources.pdap.io/search/calls/data.lacity.org/resource/iy4q-t9vr.json

However, some links work OK—the next one over takes you to a [404 page](https://data.virginia.gov/Public-Safety/Open-View-Henrico-County-Calls-for-Service/g7aq-7uu3), but at least it's _their_ 404. Is it because we're missing an http(s)?

**Comment by bonjarlow** [comment]
I think you're right, https://data.lacity.org/resource/iy4q-t9vr.json is valid, but all the "data.lacity.org" API endpoints in the airtable are missing https://

Looking more, it looks like any source_url from the openpolicedata scraper that's a JSON endpoint is missing https://, so in all of those cases the same behavior will occur.

Semi-related, I see that sometimes there's a readme_url along with the source_url. For the specific example you provided, the airtable is missing its readme_url which is below. Not sure if openpolicedata scraper missed it or those have been manually included? either way here's the readme for that one.

https://data.lacity.org/Public-Safety/LAPD-Calls-for-Service-2010/iy4q-t9vr/about_data

beyond related, it could be nice to default to the readme_url if there is one in the PDAP searcher, as the source_url for API endpoints just renders the JSON in your browser (and will only let you download the first 1000 lines if you choose to do so without modifying the URL yourself)

**Comment by bonjarlow** [comment]
bug fixed and merged!
