### ISSUE TITLE
Indicate in README that app will not run on Python 3.12

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#341]
Per @EvilDrPurple:

>  I know the README for the datasources app implies you should use Python 3.11 but trying with 3.12 the installation of packages failed due to deprecation of distutils and one of the packages relying on it. Just in case you weren’t aware already, and I wasnt sure if you think it would be worth it to add a little note saying that the application will not run on Python 3.12 in its current state

**Comment by josh-chamberlain** [comment]
The way we do it here is really professional: https://github.com/Police-Data-Accessibility-Project/design-system

https://shields.io/

might be overkill for a required python version, but we may have other things to display
