### ISSUE TITLE
Do we need as many columns in some endpoint responses?

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#359]
Certain queries, such as the `GET` method in the `DataSourceById` resource, return a large number of values. In the case of `DataSourceById`'s `GET` method, it returns 66 distinct values, which strikes me as a tad excessive. This adds burden onto testing, refactoring, and maintenance. We may want to consider whether all of these values are truly essential to our responses.

**Comment by josh-chamberlain** [comment]
Could you post an example of the 66 values you're getting, just so we're on the same page? We can probably cut some—but I would want to do it by cutting them _entirely_, not storing them in the database at all.

If we don't return all the public database properties, we have a different problem—every time there's an edge case requiring a property we keep in the database but don't use too often, we have to go add it to the API response, docs, tests, etc. If we're not going to return them in the API, what's the point of having them?

[GraphQL](https://graphql.org/) solves this by having users ask only for the properties they need. One day.
