### ISSUE TITLE
Confirm that users cannot update the password of a *different* user using their own api key and create a test for it.

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#360]
It is unclear to me if the user backend code checks to see if the API key provided to it is associated with the same user whose password is being changed. We need to double check this and develop a test to confirm the proper functionality.

**Comment by josh-chamberlain** [comment]
this is part of #162 , right? People would have the permission to change their own password, but not those of others.

**Comment by maxachis** [comment]
@josh-chamberlain You're right! I added that as a test case to the issue, and consequently will close this one.
