### ISSUE TITLE
Change date columns types to timestamp

### ISSUE THREAD

**Issue by EvilDrPurple** [Police-Data-Accessibility-Project/data-sources-app#369]
### Context

Since updating the `last_cached` column to have the type `timestamp` so that we could store more precise times, we should update the rest of the `date` columns to `timestamp` as well for more uniformity
The only column that comes to mind that should be updated is `broken_source_url_as_of` but there may be others

### Requirements

* Any columns utilizing the `date` type should be updated to `timestamp`
* On the application side, formatting should be updated to accept the time portion of `timestamp` in addition to the date
* We should also be able to streamline the following if-elif statement from `utilities/common.py`:

```python
if key == "last_cached" and value is not None:
    data_dict[key] = value.strftime("%Y-%m-%d %H:%M:%S")
elif isinstance(value, datetime.date):
    data_dict[key] = value.strftime("%Y-%m-%d")
```

### Tests

* Existing tests should point to any problems when updating particular columns to a new type

**Comment by josh-chamberlain** [comment]
would dates without a time just be set to 00:00:00 in a migration? Do we need to change anything upstream in Airtable/

**Comment by EvilDrPurple** [comment]
> would dates without a time just be set to 00:00:00 in a migration? 
Yes! Dates are automatically set to 00:00:00 when converted to timestamp
> Do we need to change anything upstream in Airtable?
I imagine eventually, once we merge the v2 database with Airtable (assuming I'm thinking about this correctly)

**Comment by maxachis** [comment]
I just went and scanned through our various database tables, and we have successfully taken care of this!
