### ISSUE TITLE
Update `DEV_DB_CONN_STRING` so that it is renamed to `TEST_DB_CONN_STRING` 

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#381]
A minor issue: `DEV_DB_CONN_STRING` should be renamed to `TEST_DB_CONN_STRING` for clarity in the following places:

* Where it is referenced in the code.
* The README
* The Github Action variable name (not the Github Secret reference, which can remain so we don't have to go through the pain of changing it)

This is as a point of clarity more than anything else, as a way to make it clear that this is for running tests. 

Alternatively, it's an open question as to whether this environment variable should be eliminated entirely in favor of keeping `DO_DATABASE_URL`. In practice, these two variables are almost always the same. However, `DO_DATABASE_URL` is used solely for functionality of `app.py`, and it may be worthwhile to maintain that separation of concerns, even if there is redundancy involved.

**Comment by josh-chamberlain** [comment]
Nice! all in favor of naming consistency! github secrets aren't too hard to change, are they?
