### ISSUE TITLE
update to new auth library

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#383]
### Context
Part of https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/318

strong relation to #335 

This is setting up basic auth and making the necessary changes to the users table.

### Requirements

- [x] implement a new auth library
- [x] support standard email + PW login
- [x] Update `users` table database to include columns for new OAuth IDs (i.e., `github_id`, `google_id`) or implement some other database update to accommodate this. 
- [x] Develop new endpoints or modify existing endpoints for OAuth utilization.  
- [x] document that user creation via the API can only be done by admins; direct people to the web-based `sign up` workflow
   - When trying to run the app locally, I need an API key. In order to get one, I need to create a user. The front end has its own API key, so let's make that the only new user workflow—and it encourages github sso!
- [x] clean up API key logic in the users table
   - it should only ever be a static API key; whether those are occasionally generated by admins is a separate matter

**Comment by maxachis** [comment]
> Update users table database to include columns for new OAuth IDs (i.e., github_id, google_id) or implement some other database update to accommodate this.

This is actually already done! A new table has been added called `external_accounts` which identifies different external accounts associated with a user!
