### ISSUE TITLE
Create a startup script to start the client and `app.py` from a single command

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#385]
Currently, to start up the client and `app.py`, I need to create two terminals. One of which has to navigate into the `client` directory and run the various npm commands in there. Another of which has to run `app.py` in the root directory.

Surely there's a way we can do both of these in a single startup script? We could then migrate some of the installation instructions to that setup script, rather than locating it within the `README` file.

**Comment by maxachis** [comment]
Eh, in retrospect, not needed.

**Comment by josh-chamberlain** [comment]
![mountaintop](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbGkyMzljNTYxazhmZDA0bjdja2l6cWw5eTB4ZW95MXY5Y3hjbGYzNSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o84sypMl9QoaJIzdu/giphy.gif)
