### ISSUE TITLE
Encrypt API Keys server-side

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#388]
While passwords are currently encrypted in the database, API keys are not. Considering that API keys enable someone to perform a number of actions as a given user and with the permissions available to that user, we probably want to address that.

We have a number of possible approaches to this, including: 
1. Utilizing the pre-existing password encryption functionality located in the backend code
2. Adding a database extension like [pgcrypto](https://www.postgresql.org/docs/current/pgcrypto.html) to the Postgres database, and handling the generation, encryption, and decryption of API keys database-side.
3. A variety of other backend- and database-side options.

## Implementation Requirements

- [x] Determine if API keys should not be decryptable by anyone but the user that API key is associated with, OR if encryption/decryption is handled centrally. 
- [x] The experience of using the `/api_key` endpoint should not be impacted -- the user should still be able to retrieve or refresh an API key as needed without going through any extra hoops.  
- [ ] We should also have a way, using secrets kept in keybase, to regenerate an admin API key in the future so that we don't lock ourselves out. We should then document that process in notion dev docs.
- [x] Additionally, for development only, we need to ensure we have a stable set of encrypted API keys provisioned for both the stage and dev environment.

**Comment by maxachis** [comment]
How to ensure proper user-specific encryption is what I'm currently noodling over. I contemplated encrypting using a hash of the user's current password, but the downside to that is that if the user's password changes, the API key must also change, otherwise the hash of the current password would do nothing.

Another option, which I'm still looking into is the (embarrassingly named) [KEK (Key Encryption Key) model](https://www.vpnunlimited.com/help/cybersecurity/key-encryption-key).

**Comment by maxachis** [comment]
Currently, I'm settling on having a single encryption key rather than a dual-encryption model: While ensuring greater security, it may be overkill in this context, as JWTs will be used for the more secure endpoints rather than API keys. 

This encryption key would be accessed as an environment variable within the app (perhaps as `ENCRYPTION_KEY`), and used to encrypt and decrypt keys via the app. 

This will also make seeding API keys for test users easier because I can use that same `ENCRYPTION_KEY` in the test user generation scripts in the [Prod-To-Dev-Migration](https://github.com/Police-Data-Accessibility-Project/prod-to-dev-migration) repository, and then provide that same `ENCRYPTION_KEY` to developers for the stage app.

**Comment by maxachis** [comment]
The general plan for creating a test app user is to use the following python script, added in `rebuild_db.py` in https://github.com/Police-Data-Accessibility-Project/prod-to-dev-migration:

```python
def create_test_user_with_elevated_permissions(admin_db_conn_string):
    print("Creating test user with elevated permissions...")
    run_command(f"""psql {admin_db_conn_string} << SQL
            BEGIN;
        
        -- Insert statements for categories and storing their IDs in variables
        DO $$
        DECLARE
            user_id INT;
        BEGIN
            INSERT INTO USERS (email, password_hash, api_key) VALUES
                (
                    'pdap_app',
                    'scrypt:32768:8:1$CJ1dfSyRRbnGbPBG$2a02614925c682232b3fe3cf558f5c9bdd9313b700f709c15e72d40e22f60cdf2020f12b3655bbd6a9ea916428c44a227eb6041164422ed234f66214d2a46981',
                    pgp_sym_encrypt('PDAP_TEST_API_KEY', '{os.environ['ENCRYPTION_KEY']}')::TEXT)
                ) RETURNING id INTO user_id;
        
            INSERT INTO User_Permissions (user_id, permission_id) VALUES
                (user_id, 1),
                (user_id, 2);
        
        
        END $$;
        
        -- Commit the transaction
        COMMIT;
    SQL
    """)
```

**Comment by maxachis** [comment]
Note that this will requiring adding an `ENCRYPTION_KEY` environment variable to the migration repo as well as to the main app repo -- this will be the key that is used to encrypt and decrypt API key values.

**Comment by maxachis** [comment]
Also, in `dev_scripts.sql`, the following will need to be included:

```sql
create extension if not exists pgcrypto;
```

**Comment by maxachis** [comment]
@josh-chamberlain For API keys, the intended use of the api keys is tied to the method of encryption, so I want to clarify which use-case we're looking for:

| Feature                                      | Users see API Key only once; hashing                                     | Users can see the same API key multiple times; reversible encryption     |
|----------------------------------------------|--------------------------------------------------------------------------|---------------------------------------------------------------------------|
| **Description**                              | - Users see their API key only once and must manage it themselves.| - Users can see their API key multiple times. |
| **When do users need to refresh their API token?** | Whenever they need to see the key again or suspect a security issue.     | Only if they want to change the key or suspect a security issue.          |
| **How is it managed?**                        | Users are responsible for storing the key securely after initial view. <br> The system uses a hashed key for validation. | Users can retrieve the key multiple times from the system. <br> The system uses reversible encryption to store and retrieve the key. |
| **Pros**                                     | - More secure                                                            | - More convenient for users                                                |
| **Cons**                                     | - Less convenient for users                                              | - Less secure                                                              |

**Comment by maxachis** [comment]
## Setting up Test API Keys

One thing I'll need to work on is ensuring API keys can stay static in the development backend even while encrypted (and with the encryption done in the middleware). 

My current idea is I pre-encrypt/hash an API key (using the same encryption key we'll use in the development environment), and then store that encrypted API key manually in the backend. The middleware apps will need to have the correct API key, but in theory, they shouldn't have to regenerate an API key every time.

**Comment by josh-chamberlain** [comment]
@maxachis your thoughts on encryption make sense; something like `pgcrypto` seems like a good option, in line with our usual strategy to use what's already been created where possible.

I think `users should only see the API key once`. It's more secure, and we will give them a way to regenerate a key if needed so the inconvenience cost is not too bad. I suspect most of our API users will not be deploying apps but working locally + individually. Also, many of our users are interested in cybersecurity!

**Comment by maxachis** [comment]
@josh-chamberlain In that case, we can probably use the same method we use for hashing our passwords and storing them in the database, which can simplify the steps required considerably!

**Comment by joshuagraber** [comment]
> I think users should only see the API key once. It's more secure, and we will give them a way to regenerate a key if needed so the inconvenience cost is not too bad. I suspect most of our API users will not be deploying apps but working locally + individually. Also, many of our users are interested in cybersecurity!

I agree. It's relatively trivial to generate and encrypt a new key, so it makes sense to only return it once.

**Comment by maxachis** [comment]
Well, that was surprisingly simpler than I thought it would be. I successfully updated the API key logic and hashed existing API keys in the database, so previous API keys from production will still work in the new format.
