### ISSUE TITLE
Change `/api_key` to `/api-key`

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#393]
This endpoint is the only endpoint which uses underscores instead of hyphens. This is inconsistent and may even cause issues. Let's fix this by having it also be hyphenated.

Additionally, let's move it to the `/auth` namespace, for better organization and to avoid routing issues.

**Comment by josh-chamberlain** [comment]
these are nice changes, and I appreciate you making the issues to close!
