### ISSUE TITLE
Bugs in `/search`: `record_type` not affecting results

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#394]
Per @joshuagraber: "I'm not seeing any difference in search results when I pass `record_categories`."

Ran on development code and can confirm this is the case.

Will need to investigate the cause as to why, and then update logic and tests accordingly.

**Comment by joshuagraber** [comment]
@maxachis FWIW, I'm still seeing this issue in my branch, which I recently updated with dev.
