### ISSUE TITLE
Create `data_request` owner logic

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#397]
For #390, we need logic to express the relationship between rows in the `data_request` table and users in the `users` table.

## When does a user own a data request?

A user owns a data request when one of the following is true:
* The user created the data request
* The user is added as an owner for a user who already owns the data request

In the current design, owners and co-owners are not differentiated -- you are assumed to either own it or not.

## How does this compare to our existing permissions logic?

Ownership logic is separate from our existing permission logic except in the case where a user might have permission logic which automatically gives them greater-than-or-equal-to ownership permissions over a data request. For example, if a user has the DB_WRITE permission and is attempting to update a data request, they will be able to update any data request regardless of whether or not they have ownership.

Excepting these conditions, ownership logic is considered separately from permission logic.

## What middleware is required?

- [x] A database client method for determining what data requests a user owns
- [x] A database client method for determining if a user is an owner of a specific data request
- [x]  Logic for determining (based on a JWT), if a user has ownership permission for a data request (or if they have other, more global permissions which supercede whether or not they are an owner). This logic will necessarily rely on the changes implemented in https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/399
- [x] And connective tissue tying all this together

## Will we have to create `user_owns_etc` tables for each new ownership case?

(Note: This discussion was originally premised on the idea that we would create a separate linking table for user ownership. At the moment, we're solely relying on a foreign key denoting the creator of the data request in the `data_requests` table. I retain this so people aren't confused by comments responding to it).

That's my current recommendation. 

Initially, I had contemplated having a more universal `user_owns_entity` table, which links user ids with other entities. However, it is more difficult to enforce foreign key constraints, and more logic is required to differentiate between different objects users can own. It would also make it more difficult if ownership is expressed in different means (for example, where a user may be co-owner, or owns only certain components, or has other levels of permissions to an object).

Having separate tables does add more overhead in the sense of more tables, but we can structure each table in a manner best suited to that particular ownership case. 

If it turns out they tend to follow similar ownership cases, we can always consolidate in the future.

**Comment by maxachis** [comment]
@josh-chamberlain What are your thoughts on this issue as I've described it? Is this aligned with how you envision the ownership logic?

**Comment by josh-chamberlain** [comment]
@maxachis 

> If it turns out they tend to follow similar ownership cases, we can always consolidate in the future.

strong agree here—no need to abstract it if I can't think of the next anticipated use case in ~10 seconds.


However: would it be simpler if the `requests` table had a `creator` column with a foreign key to the `users` table? Since we're not making a table showing ownership across many types of records, this _feels_ even simpler to me.

I'm using `creator` and `owner` interchangeably here, but actually like `creator` more.

**Comment by maxachis** [comment]
> However: would it be simpler if the `requests` table had a `creator` column with a foreign key to the `users` table? Since we're not making a table showing ownership across many types of records, this _feels_ even simpler to me.

@josh-chamberlain Certainly! This would seem to imply that only one person can be the creator/owner (creatowner?) at a time, and thus would be the only person with permissions for that data request. Is that what we want?
 
> I'm using `creator` and `owner` interchangeably here, but actually like `creator` more, regardless of how we structure this.

Creator makes them sound like gods of data requests, so I approve of this. I for one want our users to be drunk with power 🌩️

**Comment by josh-chamberlain** [comment]
@maxachis yes, another part of moving from `owner` to `creator` is that there can be only one. There may be other users who have elevated permissions related to the request, but only one user has the attribute of being the request's `creator`.
