### ISSUE TITLE
Create `@api_key_or_jwt_required` decorator and logic for determining permissions in relevant endpoint

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#399]
We already have logic for API Keys (which take `Basic` authentication) and logic for JSON Web Tokens (JWTs) (which take `Bearer` authentication). This is logic which combines both.

There are several components to this:
* Creating a decorator that can accept either an API Key or a JWT, and performs the proper validation logic for its use case
* Creating logic for determining what permissions the user has in relation to the endpoint (so as to modify what columns are viewable to them or that they can edit, for example).

**Comment by maxachis** [comment]
> Name suggestion: `permissions_required`. We don't necessarily care how users express their identity to us.
> 
> If this feels wrong, that's ok.

At the moment, we already have a `@permissions_required` decorator, which checks the user associated with provided JWT and then checks to see if they have the provided permissions. This is simultaneously a bit more and a bit less than that -- it'll be:

1. Checking if the user has a JWT or an API Key
2. Determining the level of access for the user based on that, and passing that into the inner function. 

Which adds a bit of complexity to how to name it. At the moment, I'm sticking with the above, just because it seems simplest to say what it requires.

**Comment by josh-chamberlain** [comment]
@maxachis makes total sense!
