### ISSUE TITLE
Should `typeahead_suggestions` return locations for which there is no associated data sources?

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#400]
Shoutout to @joshuagraber for bringing this to my attention

Currently, the `/typeahead_suggestions` endpoint retrieves locations based solely on whether those locations (counties, states, localities, etc.) exist within our database. They don't take into account whether the state, county, etc. exists, but we don't have any agencies or data sources associated with it. 

So there are some scenarios, such as the below, where no results are returned:

```
http -A bearer -a $VITE_ADMIN_API_KEY GET http://localhost:5000/search/search-location-and-record-type \state==Kansas county==Dickinson locality==Abilene --print=b

{
    "count": 0,
    "data": []
}
```

So do we want the typeahead endpoint to suggest locations, even if we don't have data associated with them?

### Will modifying this logic affect the speed of the endpoint?

Nope! The typeahead suggestions are derived from what is called a "Materialized View", meaning a view that runs the underlying view query ahead of time and stores the result as a kind of pseudo-table that is retrieved as easily as regular tables (while non-materialized views must rerun the underlying query every time and are thus slower). While the logic for generating the Materialized View will need to be modified, the speed at which we pull data from the materialized view after its initial generation wouldn't be affected.

**Comment by josh-chamberlain** [comment]
The short answer is "yes", but we could also reorder them to serve places with the highest number of sources first! That could happen in the materialized view, perhaps? 

None of our places is truly empty because they have agencies with homepages, and are fertile grounds for data requests.

**Comment by maxachis** [comment]
> The short answer is "yes", but we could also reorder them to serve places with the highest number of sources first! That could happen in the materialized view, perhaps?

Yep, that could happen! I could add a means to count how many sources are in each category, and add that to the materialized view. Perhaps we may even want that on display in the Typeahead Suggestions as well -- they see the suggested location, as well as how many sources are associated with that location 🧠.

**Comment by joshuagraber** [comment]
> The short answer is "yes", but we could also reorder them to serve places with the highest number of sources first! That could happen in the materialized view, perhaps?

I like this idea. Most sources first makes sense.

> Perhaps we may even want that on display in the Typeahead Suggestions as well -- they see the suggested location, as well as how many sources are associated with that location 🧠.

I like this idea, too. May want to think about a clever UI case on the search results page for when there are no results (or even redirect to the request page instead?) but yeah, I like the idea of giving the user as much info up front as possible.

**Comment by josh-chamberlain** [comment]
@joshuagraber @maxachis ok, I think the simplest solution which still helps folks is to show some copy on search results like:

"We don't know about data in this area yet, but we can help you locate it. <Make a request>.

You can also <Submit data sources> we should know about.

Here are aggregated sources which may contain information about the place you searched:"

then, we show the federal/state/county sources as already planned. 

Fortunately, we are already planning to show "upstream" results for the county and state which contain the locality, plus federally aggregated ones. This increases the chances we will show them _something_.

Does this scratch the itch?

**Comment by joshuagraber** [comment]
> Fortunately, we are already planning to show "upstream" results for the county and state which contain the locality, plus federally aggregated ones. This increases the chances we will show them something.

@josh-chamberlain Yes, I see your point, but, that's not how it currently works.

I.e. a [search for Cleveland, GA](https://data-sources-v2.pdap.dev/search/results?state=Georgia&county=White&locality=Cleveland) shows no county/state/federal results, while a [search for Georgia](https://data-sources-v2.pdap.dev/search/results?state=Georgia#state) shows quite a few.

But yeah, I'm sure that's just a matter of some API logic that @maxachis can solve for.

Could I ask for a refinement on the "no results" copy you shared above? Then I can work it into the client once the API changes are also made.

**Comment by maxachis** [comment]
> But yeah, I'm sure that's just a matter of some API logic that @maxachis can solve for.

It is indeed! 

First things first, though, to update this, I'll need to make sure the agency-data source link is kosher, so I'm working on an issue for that in #457 .

Once that's complete, I can then update this.

**Comment by josh-chamberlain** [comment]
@joshuagraber roger that. I updated my comment—it had eaten everything inside `< >` which are intended to be links to our new forms.

Just to keep the links to related issues flowing, https://github.com/Police-Data-Accessibility-Project/data-sources-app-v2/pull/94 is the previous work on this. However, I think that PR addresses the _formatting_ and not the returning of _additional upstream sources_. I could have caught that before but I played fast and loose with the approvals. @maxachis 

btw, it's so cool that we can just pass links to searches back and forth. I don't take that for granted 🎉

**Comment by maxachis** [comment]
@josh-chamberlain @joshuagraber So here's a wrench I've been noodling over -- when we talk about how many data sources are associated with a location, it's not immediately clear what "associated" means. 

Does it mean how many data sources are associated with
1. Agencies whose jurisdiction matches that location only? (e.g., for `locality` return `locality_num`
2. Agencies in that jurisdiction _or in higher order jurisdictions_  (e.g., for `locality` return `locality_num` + `county_num` + `state_num`)
3. Agencies in that jurisdiction _or in any lower order locations within that jurisdiction_ (e.g., for `county` return `county_num` + `locality_num for each locality in county`).

Maybe it makes sense to return all three, although at that point this becomes quite a wordy typeahead suggestion.

**Comment by joshuagraber** [comment]
> So here's a wrench I've been noodling over -- when we talk about how many data sources are associated with a location, it's not immediately clear what "associated" means.

@maxachis  My thinking is that we can solve for all of this.

For each location level, we return:
- That level's results, any more-specific results, and any less-specific results, with the counts applied to each locality level. The web app auto-scrolls to the level for which the user searched (or the most-specific level that has results, if no results appear at the level for which they searched).
- To determine which more-specific results to render, that's easy. If a searched-for locality is contained within a county, we return those results. If a searched-for county is contained with in a state, we return those results.
- To determine which less-specific results, that gets a little more hairy. 
 Consider: User searches for [Gulf Breeze, Santa Rosa County, Florida](https://data-sources-v2.pdap.dev/search/results?state=Florida&county=Santa+Rosa&locality=Gulf+Breeze#undefined). There are no results for Gulf Breeze. But there is one result for [Santa Rosa County](https://data-sources-v2.pdap.dev/search/results?state=Florida&county=Santa+Rosa#county), and plenty of results for [Florida](https://data-sources-v2.pdap.dev/search/results?state=Florida#state).

So then, do we return all county-level and state-level results for the Gulf Breeze search, even though the agencies in question are not headquartered in Gulf Breeze? Or do we only return higher-level results for agencies that are contained within the location level searched?

Wyt @josh-chamberlain?

**Comment by maxachis** [comment]
> So then, do we return all county-level and state-level results for the Gulf Breeze search, even though the agencies in question are not headquartered in Gulf Breeze? Or do we only return higher-level results for agencies that are contained within the location level searched?

My thinking, and @josh-chamberlain can contradict me on this, is that the end user is more likely to be interested in agencies with jurisdictional, rather than purely locational, relevance, to the location in question. Allow me to bolster my case with an intentionally stupid example:

Suppose I have an alpaca farm in Carnegie. I want to learn about what regulations impact my Alpaca farm, so I go to `adap.io` for information about Alpaca Data, and search for `Pennsylvania, Allegheny County, Carnegie`. There is an "Allegheny County Alpaca Regulations Board" whose regulations would impact my mom and alpopca farm, but it is headquartered in Pittsburgh rather than Carnegie. Even though it's not located in Carnegie, I as an Alpaca farmer probably still care about it, because it would have info relevant to my own farm. 🦙

**Comment by joshuagraber** [comment]
> the end user is more likely to be interested in agencies with jurisdictional, rather than purely locational, relevance, to the location in question

Good point, yeah, that makes sense to me.

**Comment by josh-chamberlain** [comment]
@maxachis ah, for our purposes, for now, I think we must pretend that `location` and `jurisdiction` are the same. In your example, that agency would be listed in Allegheny County in our database, with no mention of where it is headquartered (other than maybe lat/lng for mapping).

Our search is indeed intended to reveal additional `higher order` and `lower order` sources, for the reasons mentioned above and in the body of #409. However, for the purposes of this question, we are choosing which locations to list first in the typeahead. The idea is to help people find the location they are _most likely searching for, because places with more people have more data._ 

I believe this can be very simple: **A location has "associated data sources" if the agencies which belong to that specific location have data sources.** When the person makes their search, we will show them more stuff—but we don't necessarily need the _typeahead ordering logic_ to respect all that, too.

In the typeahead, most of the time, `counties` and `localities inside them` aren't going to appear in the same list unless they have the same name (which does happen, especially in smaller counties).

I appreciate your alpaca puns, but I'm kind of speechless.
