### ISSUE TITLE
Create means for programmatically displaying view/edit permissions for endpoints

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#406]
### Context

* As discussed in https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/390#issuecomment-2289244848, I determined that we could programmatically display the varying permissions for different users for the relation returned by an endpoint. 
* Therefore, let's look into developing that!

### Requirements

* Wait for an endpoint, such as #390 , to be developer which utilizes variable view/edit permissions.
* Develop the above solution
* Worth considering: How might this impact the time it takes for the swagger generation to load?
* Perhaps cache the contents initially to load as needed?

### Tests

* Test how swagger documentation appears when it loads 
* Evaluate the impact on load times. 

### Docs

* Swagger documentation will be impacted.

### Open questions

* These tables can add a lot of text real estate to the documentation -- evaluate how that looks and whether that's what we want to go for.

**Comment by josh-chamberlain** [comment]
I believe Swagger gives us the ability to hide stuff in expanding menus / accordions, so that takes care of the TMI problem. We can default to hiding things like this.
