### ISSUE TITLE
Standardize API Responses

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#415]
### Context

* Consistency is key for API usage -- if users get a certain result out of one endpoint, they'll likely expect similar results from other endpoints. We should enforce standardization early in our design to improve the user experience.
* Additionally, we should design our responses to be potentially extensible -- we may want to add additional components to our responses in the future (for example, `deprecation_warning`), and we don't want to completely distort the response result if that occurs. It's easier if additional components consist of additional key-value pairs.

### Requirements

- [ ] For `200: OK` responses for `GET` methods returning multiple results, the result should contain three key-value pairs: a `message` pair describing the response, a `count` value, describing how many values are returned, and a `data` value, containing a list of all results. For example:
```json
{
  "message": "Data successfully returned"
  "count": 3
  "data": [{CONTENT_HERE}, {CONTENT_HERE}, {CONTENT_HERE}]
}
```
- [ ] For `200: OK` responses for `GET` methods returning single results, the result should contain two key-value pairs: a `message` pair describing the response, and a `data` pair containing a dictionary of the result, for example:
```json
{
   "message": "Data successfully returned"
   "data": {CONTENT_HERE}
}
```
- [ ] For `200: OK` responses for `PUT`, and `DELETE` methods, a status message should be contained within a JSON response labeled `message`, for example:
```json
{
   "message": "Entry successfully updated"
}
```
- [ ] For `200: OK` responses for `POST` methods, a the result should contain at least two key-value pairs, a `message` pair describing the response, and an `id` pair providing the id of the value added. For example:
```json
{
   "message": "Data request created"
   "id": 513
}
```

### Tests

* Existing tests will need updated to check the results are in the provided formats.
* To make this easier, create standardized functions for checking that the result is as expected. Alternatively, look into using something like [marshmallow](https://marshmallow.readthedocs.io/en/stable/) to automatically standardize results.

### Docs

* Swagger documentation will need updated. 

### Open questions

* NOTE: These changes may break some existing logic utilizing endpoint requests.

**Comment by josh-chamberlain** [comment]
nice, this is a good idea! especially like anything that makes it show up in PR checks.
