### ISSUE TITLE
Create CRUD endpoints for `agencies`

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#417]
### Context

* Currently, the `/agencies` endpoint exists in a very limited fashion, existing only for a mass `GET` function
* We want a standardized set of endpoints like with https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/390

### Requirements

* Create a separate namespace for `/agencies`
* Update the mass `GET` endpoint to have variable column permissions
* Add a `POST` endpoint for adding agencies
* Add `/by-id/` `GET`, PUT`, and `DELETE` endpoints 
* Provide variable column permissions as necessary.

### Tests

* Typical integration, middleware, etc. tests

### Docs

* Swagger docs should be updated and conform to the standards set by https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/390

### Open questions

* Do we assume that we'll be sticking to the same logic as in https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/390?

**Comment by maxachis** [comment]
@josh-chamberlain Here is the (as yet empty) table of permissions for `agencies`. Let me know what the permissions should look like, as well as whether any columns should be added or deleted.

| column_name                     | ADMIN | STANDARD |
|---------------------------------|-------|----------|
| name                            |       |          |
| submitted_name                  |       |          |
| homepage_url                    |       |          |
| jurisdiction_type               |       |          |
| state_iso                       |       |          |
| municipality                    |       |          |
| county_fips                     |       |          |
| county_name                     |       |          |
| lat                             |       |          |
| lng                             |       |          |
| defunct_year                    |       |          |
| airtable_uid                    |       |          |
| count_data_sources              |       |          |
| agency_type                     |       |          |
| multi_agency                    |       |          |
| zip_code                        |       |          |
| data_sources                    |       |          |
| no_web_presence                 |       |          |
| airtable_agency_last_modified   |       |          |
| data_sources_last_updated       |       |          |
| approved                        |       |          |
| rejection_reason                |       |          |
| last_approval_editor            |       |          |
| submitter_contact               |       |          |
| agency_created                  |       |          |
| county_airtable_uid             |       |          |
|   id*   |  |  |
* Will need to be added.

**Comment by josh-chamberlain** [comment]
ok, updated @maxachis ! Love a blank form to fill in. To be clear, many of these can still be theoretically created by the submitter of a form for new agencies.

**Comment by maxachis** [comment]
> ok, updated @maxachis ! Love a blank form to fill in. To be clear, many of these can still be theoretically created by the submitter of a form for new agencies.

From a design standpoint, we'd just need to connect the form submission process to the web app client with the requisite permissions to write to the table! So that should be quite doable.
