### ISSUE TITLE
data sources pagination and sorting

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#419]
### Context

Makes #75 easier. In general, with a paginated endpoint, it's helpful to allow users to `sort_by`

### Requirements

- [ ] add pagination to the GET/data-sources endpoint of 100 rows (we already do this for `agencies`)
- [ ] add optional `sort_by` param which allows a user to specify a property
  - default to recent `created_at`; allowing `last_updated` would be good too
  - accept `sort_order` param which allows `desc` (default) or `asc`

### Tests

- are the most recent results returned by default?

### Docs

- the API docs should make it clear that these are options + what the defaults are

### Open questions

- would this require front-end refactoring?

**Comment by maxachis** [comment]
@josh-chamberlain This has been addressed in Data Sources. The way I've designed things, it wouldn't take too much for me to add the sorting to `Agencies` and `Data Requests` (they both already have pagination). Would you like me to do that?

**Comment by josh-chamberlain** [comment]
@maxachis Yes, I suppose that would be best for symmetry and consistency, wouldn't it! Thanks.
