### ISSUE TITLE
Create Getting Started Guide

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#420]
### Context

- Once we feel we've got our API in a comfortable spot, we'll want to develop a getting started guide to acquaint users with our API, and walk them through some of the initial steps of getting data.
- The simpler and more straightforward we can make it, the more we promote people using it.

### Requirements

- We should treat the base URL as the starting point for this guide.

### Tests

* TODO

### Docs

* TODO

### Open questions

* TODO

**Comment by maxachis** [comment]
@josh-chamberlain I'm thinking through which endpoints we would reasonably expect non-internal users to use. Here's what I've got. Anything not in these I'm assuming we aren't expecting external users to use. What do you think?

# Expect to Use

* The `GET-MANY` endpoints for `/data-sources` and `/agencies`

# Might Use

* `/archives` `GET`
* `/data-requests` `POST`, `PUT`, `GET-BY-ID`, `GET-MANY`

**Comment by josh-chamberlain** [comment]
Excellent idea! Is there any way this can go right in the API docs, at the top? 

I edited your previous comment to include `auth` and `search`, but it makes sense!

**Comment by maxachis** [comment]
> Excellent idea! Is there any way this can go right in the API docs, at the top?
> 
> I edited your previous comment to include `auth` and `search`, but it makes sense!

Not as far as I can tell, although there may be parts of the Swagger documentation I'm not yet aware of! 

I also created #547 to help us figure out the `/auth` question

**Comment by maxachis** [comment]
@josh-chamberlain I've updated the `Introduction` section in the GitBook as a means for getting started! 

One thing I'm considering is whether a small `Getting Started` repository might be useful. The rationale is that this would allow us to better ease people into a configuration by providing a configuration and more in-depth examples which could then be used to make it easier to start using the API out of the box. Folks could even clone from that API to start using it. This could eventually be expanded on or used as the foundation for an SDK, if we wanted to ever go in that direction.

**Comment by maxachis** [comment]
Note to self: After sussing it out over the finest of cuisines, me and Josh decided no on the repository, but yet on the GitBook. 

Last thing to do is to update the API documentation as Josh describes above to point to the Getting Started guide.
