### ISSUE TITLE
Migrate `HomepageSearchCache` to v2

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#428]
### Context

* The [HomepageSearchCache](https://github.com/Police-Data-Accessibility-Project/data-sources-app/blob/07913376057500c6aec450b3a4b35d848b546538/resources/HomepageSearchCache.py) exists in a weird liminal space where it's an endpoint in v1 but not in v2. 
* While this has worked temporarily, we'll need to migrate it into v2 and bring it into compliance with the various tests and documentation standards we've set up there.

### Requirements

* Bring HomepageSearchCache and associated middleware to v2
* Set up tests and docs for it as needed. 
* Revise permissions structure to v2 standards. 

### Tests

* Build basic middleware, DatabaseClient, and integration tests 

### Docs

* Set up swagger documentation for endpoint

### Open questions

* None at this time!

**Comment by josh-chamberlain** [comment]
@maxachis nice. What do you think about a "graceful" deprecation period for the v1 API where we remove endpoints that are replaced via v2? Or, do you think we should just be ready to do it all at once?

**Comment by maxachis** [comment]
> @maxachis nice. What do you think about a "graceful" deprecation period for the v1 API where we remove endpoints that are replaced via v2? Or, do you think we should just be ready to do it all at once?

I think we can do so gradually! We lose nothing but a little bit of hosting cost from having two apps simultaneously, and we'll be able to minimize friction if we can do things one at a time without being in a rush.
