### ISSUE TITLE
Update `data_sources` schema

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#430]
### Context

* The `data_sources` table in the database will need to be updated to conform to database best practices 
* Related to #429 

#### Alter Columns

- [x] `data_source_created` -> `created_at`, with default time for when it was created; type becomes `timestamp with time zone`
- [x] `source_last_updated` -> `updated_at`, with default time for when it was created; type becomes `timestamp with time zone`
- [x] Update `url_status` to accept an enum of permitted values; set default to 'okay'
- [x] Update `retention_schedule` to accept an enum of permitted values
- [x] Update `approval_status` to default to `pending`, set it to not allow null values, and create an enum for the column's acceptable values.
- [x] #466 
- [x] #467 
- [x] Other modifications?

#### Remove Columns
- [x]  `url_broken`: was replaced by `url_status`
- [x]  `approved`: was replaced by `approval_status`
- [x] `records_not_online`: was replaced by...nothing, or maybe url status
- [x] `record_type`: Replaced by `record_type_id`*
- [x] `record_type_other`: Not used
- [x] `number_of_records_available`: Not used
- [x] `size`: Not used
- [x] `private_access_instructions`: Not used
- [x] `airtable_source_last_modified`: Not used
- [x] `url_button`: Not used
- [x] `tags_other`: Not used

#### Update dependent scripts
Certain scripts which rely on the current schema will need to be checked to ensure they still perform as expected with these data source alterations. 
- [ ] *There may be scripts referencing `record_type` instead of `record_type_id`, and these should be accounted for.
* Note that some columns are less likely to have an impact on other scripts than others (for example: `url_broken`, `approved`, `records_not_online` are all not supposed to be there even now), so it may be useful to remove some of these in stages. 

### Tests

* TODO

### Docs

* Add descriptive comments to the table, all columns, and all triggers

**Comment by maxachis** [comment]
@josh-chamberlain Additionally, the `agency_described_submitted` column is _probably_ obviated now by the `agency_source_link` table, but there's a possibility that there's some information in that which is not conveyed by `agency_source_link` which we would want to maintain.

**Comment by josh-chamberlain** [comment]
@maxachis I replied by editing your comment, to keep the conversation history short
