### ISSUE TITLE
v2: typeahead for agencies selection

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#433]
### Context

Part of #252 

When submitting a new data source, you can pick an agency from our database. We need to make that typeahead. [see the form here for an example.](https://airtable.com/app473MWXVJVaD7Es/shrJafakrcmTxHU2i)

### Requirements

- [ ] this endpoint should present typeahead suggestions much like the other one, but based on our agencies database
- [ ] it should return the agency name, with `locality` `county` `state` for disambiguation

### Tests

TBD

### Docs

API docs

### Open questions

* Any uncertainties? Anything we're flexible about?

**Comment by maxachis** [comment]
@josh-chamberlain @joshuagraber 

With this in mind, I'll probably want to rework the existing `/typeahead-suggestions to maintain organization. Here's what I'm thinking:

1. Create a general `/typeahead` namespace, for which there are two endpoints:
2. `/typeahead/location` -- the previous `/typeahead-suggestions` endpoint we all know and love.
3. `/typeahead/agencies` -- the new endpoint.

(I'd also change the `typeahead_suggestions` materialized view to `typeahead_locations` and add a new `typeahead_agencies` materialized view, but that's more important for my side than anyone else's).

For @joshuagraber, this means the existing typeahead endpoint will need modified to the new design.

**Comment by maxachis** [comment]
@josh-chamberlain Do we want to include `jurisdiction_type` as well for this enpdoint?

**Comment by maxachis** [comment]
# Current Materialized View Design

```sql
CREATE MATERIALIZED VIEW IF NOT EXISTS public.typeahead_agencies
TABLESPACE pg_default
AS
	SELECT
		a.NAME,
		a.SUBMITTED_NAME,
		a.JURISDICTION_TYPE,
		a.STATE_ISO, -- State
		a.MUNICIPALITY
		c.name county_name,
		a.AGENCY_TYPE
	FROM
		AGENCIES a
	JOIN counties c ON a.county_fips::text = c.fips::text
```

**Comment by josh-chamberlain** [comment]
@maxachis 

1. `jurisdiction_type`, sure, because it might help people disambiguate. `agency_type` should not be necessary. 
2. we should search on `name`
