### ISSUE TITLE
Revise `/data-sources-map`

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#438]
### Context

* Due to a variety of changes I've been making, the `/data-sources-map` endpoint got busted.
* At the same time, however, that might be fine, because we need to figure out what to do with this, or if we still need it.
* As with other previous data sources endpoints, this references some `agencies` columns, which ~isn't viable~ is actually completely fine, but should be taken into account.
* Maybe a `views` endpoint that provides a `data-sources-map` view?0

### Requirements

* Figure out what to do with the `/data-sources-map` endpoint

### Tests

* We'll either need to revise existing tests, create new tests, or eliminate the tests we have for this, depending on what we decide to do.

### Docs

* API documentation will likely need updated.

### Open questions

* Any uncertainties? Anything we're flexible about?

**Comment by josh-chamberlain** [comment]
@maxachis We do still need the endpoint (for now). For your context, here's the primary user of the endpoint: https://github.com/Police-Data-Accessibility-Project/data-source-map/pull/15

I believe the reason for the dedicated endpoint was due to better performance in this specific use case, but probably there's an appropriate solution.

**Comment by maxachis** [comment]
@josh-chamberlain I've begun working on bringing this back online (although possibly with a different endpoint name), but I would point out that as far as performance goes, loading every single entry every time may incur some performance costs, particularly as the number of data sources/agencies we get expands. So it may be useful to think about a more substantial revision further down the line.

**Comment by josh-chamberlain** [comment]
@maxachis true...the front end should probably make use of caching, too.

**Comment by maxachis** [comment]
Note to Max: This endpoint _has_ been implemented, but it's not showing up as expected in the documentation, presumably because it overlaps with the other logic. 

To solve this, just create a new `/map` namespace, with `/data-sources` appended to it. Make others aware of this breaking change.

**Comment by maxachis** [comment]
_Now_ it's been fixed!
