### ISSUE TITLE
"de-pluralize" search terms in quick search endpoint

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#45]
### Context

Currently entering `reviews` into search would not return something like `Allegheny County Police Review Board Transcripts` because of the `s`. 

See #15 

### Requirements

* Anticipating a lot of people searching for `transcripts` and `courts` and `arrests`. Those should work for `interview transcript`, `court record`, and `arrest reports`.

### Tests

* A test case for one or two of the above terms would be good.

### Docs

* [This says plurals are no good](https://docs.pdap.io/api/endpoints/data-sources-database); we should say instead that we're forgiving.

**Comment by kalenluciano** [comment]
I can address this in [issue 15](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/15)!

**Comment by josh-chamberlain** [comment]
fixed by #46
