### ISSUE TITLE
Consolidate/Resolve `data_sources` columns `data_portal_type` and `data_portal_type_other`

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#466]
### Context

* Currently, the `data_portal_type` and `data_portal_type_other` columns in the `data_sources` table have a lot of overlap with each other.
* For example, both columns include `MuckRock` as one of their potential data portal types, and in some cases `SWIFTREPOSITORY`, `PowerDMS`, and `MuckRock` are listed simultaneously for both columns.
* We should probably consolidate these to simplify logic. But how?

### Requirements

* TODO

### Tests

* TODO

### Docs

* TODO

### Open questions

* TODO

**Comment by josh-chamberlain** [comment]
the `data_portal_other` is only used for submission; part of the intake process is noticing if there's a value there, and adding a `data_portal_type` if it wasn't on the list.

**Comment by maxachis** [comment]
Got it! In that case, I will close this!
