### ISSUE TITLE
Move `data_sources.data_source_request` content into `link_data_sources_data_requests` 

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#467]
### Context

* Currently, the `data_source_request` column in `data_sources` contains information presumably linking certain data sources with certain data requests.
* We should move this to the newly-created `link_data_sources_data_requests` column and then eliminate the `data_source_request` column from data_sources`, to eliminate redundancy.
* App-side schemas and retrieval logic will need to be updated accordingly, as will column permission tables.

### Requirements

* TODO

### Tests

* TODO

### Docs

* TODO

### Open questions

* TODO

**Comment by maxachis** [comment]
Upon closer inspection, I realized that the `data_requests` table has no `airtable_uid` column, nor does it have it in production. Similarly, `data_requests` does not mention what sources its linked to (though this is mentioned in the data dictionary). It may be possible to cross-reference this with the `data_requests` table in airtable to figure out the corresponding data requests, but it may also be overkill -- there are 66 non-null `data_source_request` column values in `data_sources`, out of over 4000 data sources. 

What do you think, @josh-chamberlain?

**Comment by josh-chamberlain** [comment]
@maxachis do we _need_ an `airtable_uid` column? We have a countup style unique `id` for requests, is that sufficient?

In Airtable, it's one of those magical two-way links between `requests` and `data sources`. It's more relevant, usually, to display which sources are related to a given request; we don't have many requests, so it makes sense that most sources would not have a request associated with them. However, many/most of our requests have associated sources.

<img width="190" alt="Screen Shot 2024-09-30 at 2 26 52 PM" src="https://github.com/user-attachments/assets/9b4ca7e7-dea9-454d-94f6-d71720135f4f">

**Comment by maxachis** [comment]
@josh-chamberlain Oh no, we don't need an airtable column, and indeed, I've been working on removing those because they're redundant with the ids. But the previous versions did have them, so that's my main reason for trying to figure them out -- once we get any potentially relevant information from the airtable columns, I'm happy just getting rid of them completely!

In this case, the big challenge is just that it seems there _used to be_ airtable columns for data requests, which were being referenced in the `data_sources` table, and it's not clear what those data requests are, or how to determine them.

If the data sources appear in their full names in airtable in the `data_requests` table, then it may be sufficient to just get a big ol' list of them and figure out how to match them -- presumably, we could match on the name or submitted name.

**Comment by josh-chamberlain** [comment]
@maxachis OK—I added a property to `data_requests` which contains the data source airtable UID, and slipped it into the data dictionary.

<img width="378" alt="Screen Shot 2024-10-01 at 11 38 07 AM" src="https://github.com/user-attachments/assets/b4d855df-953c-4317-92ed-fc3eb256d15c">

**Comment by maxachis** [comment]
> @maxachis OK—I added a property to `data_requests` which contains the data source airtable UID, and slipped it into the data dictionary.

@josh-chamberlain Got it! In this case, the path of seemingly least resistance would likely be as follows:

1. Create a column in the production `data_requests` table which corresponds to this, 
2. Update the airtable mirror to pull this data as well, 
3. Set up a special session of airtable mirror to pull ALL data requests going back to the beginning of time
4. Then proceed with the linking in stage. 

As with anything involving production, we may want to make sure we have good backups, so we may want to look into #522 as a just-in-case measure.

**Comment by josh-chamberlain** [comment]
@maxachis this appears to be a sound strategy! Let me know if you could use help with the database restore docs. Maybe I should try doing it so we can be sure it's dummy-proof.

**Comment by maxachis** [comment]
@josh-chamberlain The new branch is available for you to approve! We may not even need to approve it, since I doubt we'll have many data requests that will be linked to data sources between now and the termination of #32 , but just to stay on top of things.
