### ISSUE TITLE
Return linked agency name in Data Sources endpoint

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#47]
Following #19 

This needs to be looked up from the database. Use the quick search endpoint as a reference. The original column name in Airtable is `agency_described` so that could be used for continuity unless using it would be confusing or disrupted.

https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/19#issuecomment-1714573904

**Comment by kalenluciano** [comment]
Re-opening this issue to fix the data returned to the client to actually include the agency_name value pulled from the Data Source database
