### ISSUE TITLE
Refine Rate Limits for Select Endpoints

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#470]
### Context

* For some of our endpoints, the rate limit may be a tad too conservative. 
* For example, `/data-sources/{data_source_id}` `GET` would be called quite frequently if, on the web page, a user was quickly clicking the `PREV`/`NEXT` buttons when viewing individual data sources. The current default limit is 100 per hour, and that would be quickly exceeded due to such behavior.
* We should think about what we would like our rate limits to be in this scenario, as well as in comparable scenarios.

### Requirements

* Determine a desirable rate limit for `get-by-id`-type endpoints
* Implement that rate limit

### Tests

* TBD

### Docs

* TBD

### Open questions

* See above!

**Comment by josh-chamberlain** [comment]
Because it's probably used in bursts, `/data-sources/{data_source_id}` `GET` seems like it could be a 50-per-minute, 250-per-hour type thing. I imagine people would quickly tire of NEXTing when they could just go back to the search.
