### ISSUE TITLE
Data Source updates, approval, maintenance

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#477]
### Context

We have #74 for approving brand new sources (and requests). We should also be able to approve _updates_ to sources that come from external sources. This is more complicated.

These could come one by one, or via script. [(example of a third party script)](https://github.com/Police-Data-Accessibility-Project/data-cleaning/issues/8)

### Requirements

- [ ] allow people to propose changes programmatically or via data-sources/edit UI
- [ ] allow people to approve or deny changes

#### Option 1, Using dolthub:
- mirror our db to [dolthub](https://www.dolthub.com/), and let them handle the merge and approval process
- document the process of making suggested changes
- when changes happen in dolthub, sync them back to our production database
- **we can't do this easily because our db is postgresql**

dolthub docs: https://docs.dolthub.com/

#### Option 2, Using retool to roll our own:
- back end support for _proposed updates_
- add a page to the retool workflow for approving _proposed updates_
- deal with conflicting updates (rare but scary)
- deal with approving many things at once (seems complicated)
- **we don't need to do this, really, yet, but we could down the road**

#### Option 3, using CSV imports and exports
- **this is the chosen option; closing this issue for now**
- #511 
- #512

**Comment by maxachis** [comment]
@josh-chamberlain 

So Dolt and Dolthub is probably out, mainly because Dolt is designed for [MySQL databases](https://docs.dolthub.com/). This means that something is highly likely to break if we tried to import it into (or out of) Dolt. There is [an experimental Postgres version of Dolt](https://github.com/dolthub/doltgresql), but it is still in experimental stages and considerably limited in functionality, including lacking support for DoltHub.

So, assuming there's not something I've missed, let's turn our attention to the build-a-bear option 🐻.

First things first is -- what attributes of data sources and data requests do we envision external users as being able to propose changes to? Is it the same that we see in the `PUT` requests for `/data-sources` and `/data-requests`, or a more limited subset?

**Comment by maxachis** [comment]
Note to self: If we want to keep a record of changes, best option might be using a trigger and an audit table:


```sql
CREATE TABLE table_audit (
    id SERIAL PRIMARY KEY,
    operation VARCHAR(10), -- 'INSERT', 'UPDATE', 'DELETE'
    changed_data JSONB,    -- Store data in JSON format
    changed_by VARCHAR(50), -- If you track the user making the change
    changed_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION track_changes()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO table_audit (operation, changed_data)
        VALUES ('INSERT', row_to_json(NEW));
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO table_audit (operation, changed_data)
        VALUES ('UPDATE', row_to_json(NEW));
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO table_audit (operation, changed_data)
        VALUES ('DELETE', row_to_json(OLD));
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON your_table
FOR EACH ROW EXECUTE FUNCTION track_changes();
```

**Comment by maxachis** [comment]
Also note to self: To create a backend of this, create `proposals` tables which can store information about the proposal:

```sql
CREATE TABLE proposals (
    id SERIAL PRIMARY KEY,
    main_table_id INT NOT NULL, -- foreign key to the main table
    proposed_changes JSONB NOT NULL, -- stores the proposed changes
    description TEXT, -- description, if any, of the changes. 
    created_by INT NOT NULL, -- user ID of the proposer
    created_at TIMESTAMP DEFAULT NOW(),
    status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'approved', or 'rejected'
    reviewed_by INT, -- ID of staff who reviewed the proposal
    reviewed_at TIMESTAMP
);
```

We could potentially just delete the proposals after they're made, but that's a lesser question.

**Comment by maxachis** [comment]
Note to self: Possible scenarios to consider:

* Suppose a proposal is submitted, but then the table schema changes in a way that renders at least one of the proposed changes invalid? A probably rare occurrence, but worth musing over, however briefly.

**Comment by maxachis** [comment]
After an intense series of interpretive dance with @josh-chamberlain, the decision is as follows:

1. Create endpoints for csv imports for mass inserts OR updates of data sources/data requests/agencies. So this will cover #511 
2. Mass-inserts can be done by any automated user, and results will have to be approved
3. Mass-updates can only be done by users with admin permissions, and persist immediately.
