### ISSUE TITLE
set up recurring notifications architecture with mailgun and github actions (or similar)

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#478]
Part of #26 

## Endpoint Design

`/notifications/followed-searches`  `POST`, when called, sends all notifications for the past month.

## Notification Architecture

- [ ] Should occur on the first of each month, and retrieve all relevant updates starting from the first of the _previous_ month.

## Email Design
- [ ] Data Sources and Data Requests should be provided as a list of the relevant Data Sources and Data Requests, including their name/title and nothing else.
- [ ] For Data Sources, should be prefaced with "The following Data Sources associated with your subscribed locations have been added..."
- [ ] For Data Requests, should be prefaced with "The following Data Requests associated with your subscribed locations have recently been made" and "The following Data Requests associated with your subscribed locations have recently been completed."
- [ ] Data sources/requests should be hyperlinks to the associated data source/request on the website
- [ ] Include a link to the person's user profile

## Supporting Issues
- #479
- #481 

## Succeeding issues
- [ ] #493

**Comment by josh-chamberlain** [comment]
I agree that Option Source is nice; I think the name for sources / requests should be a hyperlink. We should also link people to their profile (containing followed searches) from the template, so they can effectively manage their notifications.

**Comment by maxachis** [comment]
> I think the name for sources / requests should be a hyperlink

@josh-chamberlain In that case, I'll need to get clarification from @joshuagraber as to the template I should structure these hyperlinks to data requests/data sources.

**Comment by maxachis** [comment]
@josh-chamberlain I'm done with the meat and potatoes logic and am now working on the formatting of the email we'll be sending -- which raises the question -- how much effort do we want to put (now or later) into styling everything? We can keep it simple text with some headers, or we could add a div and other elements to make it mobile optimized or use PDAP colors, etc.

For now, I'll focus on just providing the information, but good to keep the rest in mind.

**Comment by josh-chamberlain** [comment]
I am a firm believer in near-plaintext email. headers are OK, bolds and italics, a font color or two. it's very difficult to reliably style email, and the simpler it is the easier it will be to maintain.

**Comment by maxachis** [comment]
@josh-chamberlain Got it. Here's the current visual design for the email:

![image](https://github.com/user-attachments/assets/ef87882b-5541-43fe-a550-aee99a6270fb)

```html
<p>There have been updates to locations you've followed.
</br>
<h1>New Data Sources Approved</h1>
<p>The following data sources associated with your followed locations have been approved:</p>
<ul>
	<li><a href="www.google.com">Test Data Source 1</a></li>
</ul>
</br>
<h1>Data Requests Ready to Start</h1>
<p>The following data requests associated with your followed locations have been marked as 'Ready to Start':</p>
<ul>
	<li><a href="www.google.com">Test Data Request 1</a></li>
</ul>
</br>
<h1>Data Requests Completed</h1>
<p>The following data requests associated with your followed locations have been completed:</p>
<ul>
	<li><a href="www.google.com">Test Data Request 2</a></li>
</ul>
</br>
<p>Click <a href="www.google.com">here</a> to view and update your user profile.
```

**Comment by joshuagraber** [comment]
@maxachis @josh-chamberlain Yeah, emails are a pain to style, but it is somewhat commonplace these days for emails to be pretty. 

My initial suggestion to use handlebars templates was to make it more or less set it and forget it. Once a template is styled, it shouldn't need updating. The spec rarely changes (which is of course why we can't use flex or grid or any of the other modern CSS).

Of course, we could always add the templating infrastructure later if we decide we want to send emails with images and full formatting, etc.

**Comment by joshuagraber** [comment]
> I should structure these hyperlinks to data requests/data sources.

@maxachis The data sources are at `/data-source/{id}`.

For the requests stuff, that's not implemented yet, and I'm not sure quite how I'm going to do it because so much is in flux. 

@josh-chamberlain Do we have an idea of where this requests UI is going to fit into the whole application? Like, is it a part of the user profile? Or is there a "following" section, where a user has information on locations / agencies they follow? If we know that, I can speak to this a bit more fully.

**Comment by maxachis** [comment]
@josh-chamberlain @joshuagraber Similarly (and apologies for not mentioning this earlier), what about a link to the user's profile?

1. Is that set up?
2. What would the link be structured like?

**Comment by joshuagraber** [comment]
> Similarly (and apologies for not mentioning this earlier), what about a link to the user's profile?

Ah, good point @maxachis 

User profile will be at `/profile` - shouldn't need anything dynamic there, as there can only be one user signed in to the web app at a time.
And after discussion in the weekly meeting today, let's render each request by ID at `/request/{id}`
