### ISSUE TITLE
bug: v2 search not working in prod

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#484]
### Context

https://data-sources-v2.pdap.dev → search works as expected
https://data-sources-v2.pdap.io → search clears the search and does not proceed to the next page

console says: 

```
 Failed to load resource: the server responded with a status of 500 ()
```

https://data-sources-v2.pdap.io/api/search/search-location-and-record-type?state=Pennsylvania&county=Allegheny

{"message": "Please provide an API key in the request header in the 'Authorization' key with the format 'Basic <api_key>'"}

### Requirements

ID the bug, and fix it

**Comment by maxachis** [comment]
Let's check back in on this after the following pull request is complete:

https://github.com/Police-Data-Accessibility-Project/data-sources-app-v2/pull/151
