### ISSUE TITLE
Bring Vue App up to date

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-sources-app#49]
### Context

We've made some changes to the API since the app was last updated, it will no longer return results properly

### Requirements

- Create an API key for the app, include it in the requests to the API, ideally without exposing it in the browser
- Update variables referencing the deprecated "County" field to "Location"

### Tests

* Ensure results are returning and displaying properly

### Docs

* N/A

### Open questions

* Not sure how best to protect the API key

**Comment by kalenluciano** [comment]
I updated the Vue app with the API key and changing the "county" field to "location". As for protecting the API key from being exposed in the browser, I'm not too sure how to fix that. We could have each user sign up and login to create their own API key, but I think that would create a barrier for people who just want to use the quick search feature. I wonder if we could just not require an API key for some of the routes that are just reading the database (ie quick search) and only use the API key for protecting the database from being written/updated on.

**Comment by mbodeantor** [comment]
@josh-chamberlain Do you know of a way to hide the API key in the request on the browser side?

**Comment by josh-chamberlain** [comment]
@mbodeantor Do environment variables in DigitalOcean not handle this? I thought their app platform functioned like middleware, so it's using our envars to prevent them from ever being in the browser.

**Comment by mbodeantor** [comment]
@kalenluciano looks like this might be a way to address it: https://stackoverflow.com/questions/43242730/vuejs-and-vueresource-removing-header-fields-from-a-ajax-request

**Comment by kalenluciano** [comment]
I tried following the stackoverflow post, but I ran into a couple issues. The post is a bit old and based on VueJS2 (and we're using VueJS3), so I had to use axios' built-in config interceptor, which seemed to be similar to what VueResource does. However, once I got it set up, I still was able to see the API key in the request. I can push the code for your reference.

To your reply earlier @josh-chamberlain, **all** requests made through the app, including the quick search functionality, are routed through the Flask API. Currently, we ensure the security of our API and the underlying Data Source database, which is both read from and written to by the API, by enforcing the requirement of a valid API key for every request. This is achieved through the '@api_required' decorator, applied to every route, including quick search, retrieving all data sources, and fetching all agencies.

To my understanding, our goal is to allow anyone to use the quick search functionality, while maintaining restrictions on write or update operations. If this is the case, we could consider removing the API key requirement for quick search requests. Anyone would be able to search the database for information via the quick search, but modifications or write operations would remain restricted with an API key that users would have to register for. This is what I've done in past projects.

**Comment by josh-chamberlain** [comment]
@kalenluciano I think we're on mostly the same page, using slightly different terminology. Anyone should indeed be able to use the quick search interface—these users would not be logged in or authenticated, so our front end app would be the authenticated API "user". If we don't require an API key, we won't know who's using which endpoint for what and we're somewhat vulnerable.

Either way, some day soon the front end is going to need to make authenticated POST requests to make changes to data sources, create users, etc. so we can't have it displaying API keys. Are the keys getting bundled with the front end during build? Thoughts on my numbered points above?

**Comment by kalenluciano** [comment]
Gotcha, that makes sense. The API key isn't getting bundled with the front end during build because we store it as an environment variable. Once we deploy it, we'll have to add it in as a secret variable. As Marty pointed out though, users can still see the API key in the header for each request sent to the API. 

To the numbered points above, I agree that we want to keep the API key between server-to-server communication. For this to happen, I think we need to add to our authentication system in the API by encoding the API key into a JWT token that we can decode and verify in our API for each request. This way, the only thing the user sees in the header of their requests is an encrypted version of the API key that only the API can decode with a SECRET key. I can try working on this today and report back.

**Comment by kalenluciano** [comment]
I just sent [another PR](https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/52) (now attached to this issue) that builds out our authentication system using JWT tokens. Previously, we were creating an API key and using that to verify an authenticated user. The problem with this is that the frontend needed to have the API key and send it in the headers of each request, exposing it to users. 

This PR fixes the problem by creating a JWT token at log in. The token contains the API key, but it's encoded using a SECRET_KEY that only the API has access to (and is never sent to the frontend). Each request from the frontend will need to send the JWT token to the API. From there, the API will first verify that it's a legitimate JWT token using the SECRET_KEY and then after verifying, the API will extract the API key from the token and use that to interact with the database.

I tested this locally and it worked for me. You'll need to run `pip install -r requirements.txt`, include the SECRET_KEY in the API .env file, and include the JWT token in the Vue .env file. Let me know what you both think @josh-chamberlain @mbodeantor
