### ISSUE TITLE
Standardize auth token responses

### ISSUE THREAD

**Issue by joshuagraber** [Police-Data-Accessibility-Project/data-sources-app#491]
### Context

There are several paradigms for auth API responses with access tokens and refresh tokens. Originally this was built without refresh tokens (not a great idea). @maxachis updated the `/login` endpoint to return this:

<img width="536" alt="Screenshot 2024-10-23 at 9 07 27 AM" src="https://github.com/user-attachments/assets/6ac26134-5883-453f-96ce-e2ff10192aa3">

But the `/refresh_tokens` endpoint still returns this:

<img width="542" alt="Screenshot 2024-10-23 at 9 07 34 AM" src="https://github.com/user-attachments/assets/e8343c4c-b67c-4061-a4d5-6c981bc84e79">

### Requirements

- Standardize access/refresh token responses to use the following shape:

```
{
  access_token: String,
  refresh_token: String,
  message?: String
}
```
- Move `/login` and `/refresh_tokens` into the `/auth` namespace.

### Tests

I'll leave that up to @maxachis 

### Docs

- Add docstrings to generate endpoint API docs

### Open questions

- Not at the moment

**Comment by maxachis** [comment]
@joshuagraber Should I assume this also means that we will be regenerating the refresh token and invalidating the prior one when `/refresh-session` is called? That appears to be the standard, from what I've glanced at, but I want to double check.

**Comment by joshuagraber** [comment]
Yes @maxachis, I think that's usually the best way to go about it.
