### ISSUE TITLE
Clarify `data_sources.update_method`

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#497]
### Context

The `update_method` attribute of `data_sources` currently possesses one of three values (as well as `null`):
* "Insert"
* "Overwrite"
* "No updates"

It is unclear how open-ended update methods are, and if we expect others. If we don't expect it to be open ended, we may want to limit the number of possible inputs for ease of use

### Requirements

* Determine if `update_method` is comprehensive, and if we want to have update methods be specified by selecting from one of several options, or by inputing open-ended text.

### Tests

* Not applicable

### Docs

* Not applicable.

### Open questions

* See above.

**Comment by josh-chamberlain** [comment]
@maxachis Let's call this one a `select` with these 3 options. That's how it is in Airtable, which I think we can match.

**Comment by maxachis** [comment]
Perfect! As it turns out, I already have an enum encoding that, so we're all good here!
