### ISSUE TITLE
Automate `data_sources.last_approval_editor` logic to be automatically generated

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#499]
### Context

* Currently, the `last_approval_editor` logic of `data_sources` is a string value which must be manually provided. 
* This could be automated such that the last_approval_editor is determined automatically during the API call
* It may also be useful to convert this, in the database, to an integer foreign key linking `last_approval_editor` to the `users.id` column. 

### Requirements

* Determine the best approach to the above column.

### Tests

* Tests would need modified (or created) if the above logic were to change.

### Docs

* API documentation would be updated for various `/data-sources` endpoints, and possibly for other endpoints which pull data sources

### Open questions

* See above

**Comment by josh-chamberlain** [comment]
@maxachis yes, fantastic catch. this is sort of a part of #32, because it's a field that is automatically updated by Airtable—but it need not be manual in v2.

**Comment by maxachis** [comment]
@josh-chamberlain With this, I want to get some clarification:

1. Do we expect anyone aside from admins to be able to modify these data sources?
2. Do we want to record solely who changed approval status, or who modified any value, or both separately?

**Comment by josh-chamberlain** [comment]
@maxachis 

1. maybe eventually, but not right now
2. last_approval_editor should be only related to approval status. full edit history might happen in #477

**Comment by maxachis** [comment]
@josh-chamberlain For the moment, I intend to convert the existing `last_approval_editor` column to `last_approval_editor_old` for posterity. However, I can remove it entirely, as you desire.

**Comment by josh-chamberlain** [comment]
@maxachis how about just listing _me_ as the approver for all of them? It's...true

**Comment by maxachis** [comment]
Got it! It would just be a matter of assigning all of them to your user id!
