### ISSUE TITLE
Update `data_requests` PUT logic and tests 

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#504]
### Context

* Like #503 , some parts of `data_requests` `PUT` logic are not accounted for:
* Selective edit permissions do not exist for `github_issue_number` or `github_issue_url`
* API Documentation is out of date
* Integration tests do not currently test all parameters

### Requirements

* Address the above issues in a manner most pleasing

### Tests

* Some tests will be updated as per above

### Docs

* API documentation will be updated as per above

### Open questions

* No open questions at this time.

**Comment by maxachis** [comment]
@josh-chamberlain This does raise a question: Since we already have logic which separately creates a `github_issue_number` and `github_issue_url`, do we also want that to be editable within the `PUT` request? I could foresee that as being useful for maintenance, but maybe we only want it to be creatable via the automated endpoint, and not accidentally modified.

**Comment by josh-chamberlain** [comment]
@maxachis yes, it's probably good to be editable for easy maintenance—but it's tricky because `issue number` and `issue url` would need to be edited together, right? I'm actually not clear on why we need _both_ of those. Maybe there's a fancy way to account for editing just one of them.

**Comment by maxachis** [comment]
> @maxachis yes, it's probably good to be editable for easy maintenance—but it's tricky because `issue number` and `issue url` would need to be edited together, right? I'm actually not clear on why we need _both_ of those. Maybe there's a fancy way to account for editing just one of them.

That was a design decision on my part (which as we all know are unimpeachable and perfect). The reason I did so was because, otherwise, I needed to either extract the issue number or construct the issue url on every query related to them, which struck me as questionable. 

That may have been the wrong decision, and we can always adjust it, if needed.

**Comment by josh-chamberlain** [comment]
@maxachis makes sense to me. Extracting the issue number seems most workable—especially because we'll always link to the URL. I'm not even _sure_ we'll need to show the number in-app. It's fine to leave it for now, probably!
