### ISSUE TITLE
Set `external_accounts` foreign key to users to be `ON DELETE CASCADE`

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#506]
### Context

* Currently, if we delete from the users table, and the user in question has a row in `EXTERNAL_ACCOUNTS`, the deletion will be blocked because of that. The corresponding row in `EXTERNAL_ACCOUNTS` must be deleted first
* We can get around this by setting the foreign key in `EXTERNAL_ACCOUNTS` to `ON DELETE CASCADE`

### Requirements

* Set the `user_id` foreign key in `EXTERNAL_ACCOUNTS` to `ON DELETE CASCADE`

### Tests

* All tests should continue to run as expected

### Docs

* No documentation should be affected

### Open questions

* No open questions

**Comment by maxachis** [comment]
Currently made a minor adjustment to the dev_script to enable this, and pushed it directly to main. Not the most kosher, but figured I could get away with it since it's so minor, and can easily revoke it otherwise. Won't be able to do that in the future, but since it's still in dev, weeeee!

**Comment by josh-chamberlain** [comment]
@maxachis I feel a duty to follow up—how did this turn out?

**Comment by maxachis** [comment]
> @maxachis I feel a duty to follow up—how did this turn out?

Totally fine! Everything subsequently passed without issue!
