### ISSUE TITLE
CSV export for searches

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#512]
### Context

- Part of #32 
- Related to https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/511

### Requirements

- For a given search, we should be able to trigger a CSV export.
- This should probably accept search terms and use the search endpoint, to reduce the possibility that a search could disagree with an export

### Tests

- Export format must work for import format; vice versa

### Docs

TBD

### Open questions

?

**Comment by maxachis** [comment]
Shouldn't be too terribly difficult -- while the search results are divided into `federal`, `state`, `county`, `locality`, they are otherwise quite flat, so I could determine a means to convert them into a csv-friendly format.
