### ISSUE TITLE
Fix bug in `/password-reset` in production

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#518]
### Context

related: https://github.com/Police-Data-Accessibility-Project/data-sources-app-v2/pull/159
related: https://github.com/Police-Data-Accessibility-Project/data-sources-app-v2/pull/145

Currently the `/password-reset` link in **V2 PRODUCTION** is 🐛. Here's what @josh-chamberlain recently received as a password reset email:

```
https://data-sources-v2.pdap.ioreset-password/2476f29c416e482baef5ce1aa1c37d7c
```

This would lead to a nothing link, and is therefore something we need to adjust.

Additionally, our current tests are failing to pick up that this is a problem, and that will need to be addressed as well.

### Requirements

* Update test for `/reset-password` or create a new test that properly fails when this occurs, to catch this sort of bug.
* Then fix the issue so that the test passes.

### Tests

* See above

### Docs

* No change in API documentation required

### Open questions

* Is there a frontend component to this bug that exists as well?

**Comment by josh-chamberlain** [comment]
related: https://github.com/Police-Data-Accessibility-Project/data-sources-app-v2/pull/159#event-15228378386

**Comment by josh-chamberlain** [comment]
@maxachis I'm confused—this was happening in v2 for me. I _think._ That's why I got the v2 reset link. I was testing on data-sources-v2.

**Comment by maxachis** [comment]
Oh. Well in that case, we fixed it! I think? I'll have to double check.
