### ISSUE TITLE
Practice database restore at least once so we know how to do it

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#522]
### Context

Digital ocean has a database restore property. Let's make sure we know how to use it properly, so we don't have to learn at a time where we're under pressure to restore _FAST_

### Requirements

* Test database restore on sandbox or stage environment to confirm it functions properly

**Comment by josh-chamberlain** [comment]
I believe this is a good candidate for the notion docs!

**Comment by maxachis** [comment]
@josh-chamberlain Updated! I tried restoring from backup, and documented the process here! It's fairly simple.

https://www.notion.so/pdap/Restoring-From-Backup-14880fce1fec808b9784f9c7151d59c1

**Comment by josh-chamberlain** [comment]
@maxachis lovely! I converted it to a numbered-steps format so that it's a followable process, including your important notes (one does not simply skip steps in a process)

**Comment by maxachis** [comment]
@josh-chamberlain 
![image](https://github.com/user-attachments/assets/26f0f912-1d78-4187-b9e6-6ba30d648cd6)

**Comment by josh-chamberlain** [comment]
@maxachis haha, perfect
