### ISSUE TITLE
Should data sources also have a `creator_user_id`?

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#530]
### Context

* In `data_requests`, we have a `creator_user_id` to identify who created a data request.
* Since we are also giving users the ability to create data sources, should this also have a `creator_user_id`?

### Requirements

* Determine the answer to the above question
* If an affirmative, implement.

### Tests

* TODO

### Docs

* TODO

### Open questions

* See above

**Comment by josh-chamberlain** [comment]
I don't think we need it! I think these have shared ownership and go stale quickly.

**Comment by maxachis** [comment]
Alright! This is my favorite kind of issue -- the kind we don't have to do!
