### ISSUE TITLE
v2: new data source enhancements

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#533]
### Context

Follows #252 

We have a baseline of a few important properties, but there are many potentially useful fields in the schema.

#### misc improvements
- [x] mark required fields as "required" or use an asterisk
- [x] when a URL is pasted, let's check in the background to see if we already have it in the db
  - we do have a duplicate URL checking endpoint
  - for duplicates, display a message: "We already have this URL in the database, with an approval status of `<status>`."

#### adding more fields

- [see the airtable form for an example](https://airtable.com/app473MWXVJVaD7Es/shrJafakrcmTxHU2i) of how this works currently, with conditional logic and all.
- [x] show advanced properties this is not in the wireframe, but let's add a secondary button next to "Submit data source" for "Show advanced properties"
   - Rationale: these fields are all firmly optional, and showing them is intimidating for someone who's just trying to submit a source real quick. However, sometimes they are useful and power users who submit many sources will want to access them.
   - [x] clicking the button should reveal the hidden properties and keep the submit button-stack down at the bottom; it should turn into a "Hide advanced properties" button
- [x] follows the same conditional logic for "agency supplied data `no`" and "agency originated data `no`" where those properties are shown
- [x] shows "other" string field for "data portal type `other`"
- [x] instead of the "Agency not found" form field, can we work this into the typeahead? If they can't find the agency there, we can submit the user input in the `agency_described_submitted` field
- [x] consider: `select` menus are [tricky to support, and not always the best user experience.](https://medium.com/@kollinz/dropdown-alternatives-for-better-mobile-forms-53e40d641b53) we should think carefully about each property which currently uses one, and whether it should be something else.
- [ ] When the form is reset or submitted, if the additional properties are shown, it should ideally refresh _in that state_ so that a person submitting many sources with additional properties doesn't have to keep clicking it.

#### current properties

`source_url`
`readme_url`
`agency_described`
`submitted_name`
`description`
`submitter_contact_info`

#### advanced properties

- `detail_level`
- `record_type`
  - radio instead of select; can we go to multiple columns, or group them according to the categories?
- `agency_supplied`
  - conditional: `supplying_entity` and `agency_originated`
    - conditional: `originating_entity`
- `access_type`
- `record_format`
- `update_frequency`
   - radio instead of select
- `update_method`
- `coverage_start`
- `coverage_end`
- `retention_schedule`
  - radio instead of select
- `data_portal_type`
  - conditional: `data_portal_type_other`
- `access_notes`
- `submission_notes`

**Comment by joshuagraber** [comment]
> retention_schedule
radio instead of select

> record_type
radio instead of select; can we go to multiple columns, or group them according to the categories?

@josh-chamberlain Yes, of course. However, since I've already built the select menu for the new request route, and have added support for the full searchable combobox spec as well, would you prefer to use that for either of these?

**Comment by josh-chamberlain** [comment]
@joshuagraber I appreciate you doing that! Sometimes we may need to use a select, but I think for those, it would be best to just use radios! 

For `record_type`, can we split/group the options like I suggested? Here's how we do it in labelstudio: 

<img width="635" alt="Screen Shot 2024-11-21 at 2 13 30 PM" src="https://github.com/user-attachments/assets/683d89da-736d-431d-aa58-72b133175bad">

Failing that, some other way of grouping them in a select or typeahead would be great. Like an `optgroup`: https://www.w3schools.com/TAgs/tryit.asp?filename=tryhtml_optgroup

If that doesn't work in a relatively simple way, a typeahead would probably be best? I'm not too picky about how it works _exactly_, what do you think?

**Comment by joshuagraber** [comment]
> If that's not convenient, a typeahead where you can see the options would probably be best. Failing that, a simple select will work! I'm not too picky about how it works exactly, what do you think?

This all makes sense to me, @josh-chamberlain. It's just as easy to implement with radio buttons. The select menu I built isn't currently set up to behave with the optgroup-like functionality but I can add it if we decide to go that route in the future.
