### ISSUE TITLE
Switch over to v2 health monitor

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#538]
### Context

We have a health monitor for v1 -- we'll need a health monitor for v2!

### Requirements

* Set up health monitor for v2 which routinely pings one of the typeahead queries for activity.

### Tests

* Anything we should test for? How should it be tested?

### Docs

* What docs should be updated? Link to related docs changes in the PR.

### Open questions

* Any uncertainties? Anything we're flexible about?

**Comment by maxachis** [comment]
Health Monitor Created, along with another automation task!

Created! I haven't yet deployed it because v2 Prod is not yet ready for it, so it now exists as a branch off main. 

Once v2 Prod is in its final position, the next steps are:
1. Set up Health Monitor v2 automation job to use the proper variables, if any need adjusted (most likely is making sure GitHub Branch is correct and setting up the schedule)
2. Remove Health Monitor v1 Automation Job and rename "Health Monitor v2" to "Health Monitor"
3. Merge draft pull request above into main
4. Test health monitor to ensure it's working.

**Comment by josh-chamberlain** [comment]
@maxachis wonderful! I have added this to the main v2 issue so we don't forget.

**Comment by maxachis** [comment]
Forgot to update this, but this has been successfully done!
