### ISSUE TITLE
Fix `/user` `PUT` password reset

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#539]
### Context

Currently, `/user` `PUT` has a big, glaring security flaw, which is that it allows the user to reset their password _without requiring anything but their email and API key_. This absolutely must be resolved prior to v2 launch.  

### Requirements

* Move `/user` `PUT` into the `user` namespace for consistency
* Update the endpoint so that it requires a JWT (i.e., the user must be logged in)
* Update the endpoint so that it requires the user's existing password, as well as the new password
* Update tests accordingly

### Tests

* Tests will need updated accordingly 

### Docs

* API documentation will need updated

### Open questions

* @joshuagraber Is there a frontend component that's currently using this endpoint?

**Comment by joshuagraber** [comment]
@maxachis Yes, we are using this endpoint on the `/change-password` route. It's an authenticated route, so absolutely it should be gated by JWT.

Here is the method that's using it, where the constant `CHANGE_PASSWORD_URL` equals this endpoint.

```js
async changePassword(email, password) {
  const auth = useAuthStore();
    await axios.put(
	CHANGE_PASSWORD_URL,
	  { email, password },
	    {
	      headers: {
		...HEADERS,
		Authorization: `Bearer ${auth.$state.tokens.accessToken.value}`,
	      },
	    },
	);
  return await auth.loginWithEmail(email, password);
},
```

So the client is already passing this auth, as I was expecting it to be gated by JWT already. TLDR: client is g2g here (with the small chore of updating the endpoint constant once you make the change on the API side), and I agree this is a blocker for launch.
