### ISSUE TITLE
make backup storage more robust

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#541]
Part of

* #456 

Requirements
Per @josh-chamberlain: we don't _need_ frequent backups going back in time, but what if we had something like: frequent backups for the past 7 days; weekly for the past month; monthly for the past 6–12 months?

**Comment by maxachis** [comment]
Best candidate for this are [Digital Ocean Snapshots](https://docs.digitalocean.com/products/snapshots/)! Perusing through more now...

**Comment by maxachis** [comment]
Alright! I've done the following for this:

1. Update the [prod-to-dev migration repository](https://github.com/Police-Data-Accessibility-Project/prod-to-dev-migration) (which will eventually need renamed) to include backup and restore logic.
2. Create a Digital Ocean Bucket called `prod-db-bucket`, with two sub-directories, `Monthly` and `Weekly`, which are designed to contain the last 12 (for monthly) and the last 5 (for weekly) backups.
3. Set up two automation.pdap.io jobs, one for populating the `Monthly` directory with a backup (and running once a month), and one for populating the `Weekly` directory with a backup (and running once a week). 
4. Set up an automation.pdap.io job for restoring the production v2 database from a backup, which requires only specifying the path of the backup within the `prod-db-bucket`. I also ran it to confirm it functions as expected.

**Comment by maxachis** [comment]
@josh-chamberlain In addition to the backup, I suspect it may be useful to schedule a regular backup rehearsal every now and then. This would be as simple as running the automation job with the proper parameters to confirm everything still works as expected. We may not necessarily need to do that _on_ the production database -- we could briefly create another database cluster and restore to that. 

How we would formalize that schedule, though, I'm not yet sure!

**Comment by josh-chamberlain** [comment]
@maxachis well, fantastic! I will add a calendar event which will also create a discord event for rehearsing this. It will point to the `restoring from backup` notion page. Does that one need to be updated to account for the new features?

**Comment by maxachis** [comment]
> @maxachis well, fantastic! I will add a calendar event which will also create a discord event for rehearsing this. It's set to repeat every 6th month on the 1st Monday. It will point to the `restoring from backup` notion page. Does that one need to be updated to account for the new features?

It does, and I just updated it in response to you saying it needs to be updated! The marvels of human communication ✨
