### ISSUE TITLE
List when admin or ownership permissions required for different endpoints

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#546]
### Context

Currently, a number of endpoints, such as `/agencies` `PUT`, require ADMIN permissions, but do not mention this. This will likely confuse users, and should be adjusted.

### Requirements

* Update endpoint documentation so that it is made clear which endpoints require admin permissions.
* A simple way to do this might be to automatically have "Requires Elevated Permissions" appended to the description of the documentation, when the authentication information includes an admin permission

### Tests

* Tests should not need modified

### Docs

* Documentation will be updated.

### Open questions

* None at this time.

**Comment by josh-chamberlain** [comment]
@maxachis yes, automation for this sounds right to me! Keeping track of them all and remembering to update the docs is asking for trouble.
