### ISSUE TITLE
Rework `/api-key` endpoint?

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-app#549]
### Context

* The `/api-key` endpoint is currently a little unusual, in that, like the `/login` endpoint, it accepts the email and password. 
* That means two different endpoints where the user has to use their login and password. 
* This may be redundant -- why not have users log in using `/login` and pass the access token to `/api-key`?
* This may also make things easier for the web app

### Requirements

* Determine the answer to the above question
* If we need to change the input, change it.

### Tests

* If we need to change it, tests will need updated

### Docs

* If we need to change it, documentation will also need updated

### Open questions

* See above!

**Comment by joshuagraber** [comment]
@maxachis Yeah, I think your suggestions here make a lot of sense. For the purposes of the web app, `/api-key` would only be called for an auth'd user. And anyone else interacting with the API could easily set up scripting or automation with Postman or whatever to manage sessions and use their access token for subsequent requests, thus making this endpoint easier to use.

**Comment by josh-chamberlain** [comment]
@maxachis cosigned what y'all said!
