### ISSUE TITLE
Endpoint to match agencies for submission

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#550]
## Context

- related to https://github.com/Police-Data-Accessibility-Project/scrapers/pull/246
- related to https://github.com/Police-Data-Accessibility-Project/scrapers/pull/245

We have tools which generate batches of Data Sources to submit to our db. The biggest hurdle is typically that agencies out in the world aren't named the exact same thing as they are in our database; we need an `agency_described` which matches our database. There are 3 potential things that can happen:

- `* happy`: the name is exactly the same in our database, and we get a single match. hooray!
- `~ different`: the agency exists in our database by a different name.
- `+ new`: the agency does not exist in our database and we need to add it.
- `x unknown`: we don't even have an `external name` for the agency; we have no idea what to guess. that's out of scope but begun here: https://github.com/Police-Data-Accessibility-Project/data-source-identification/pull/15

## Requirements

- [ ] make an `agency-match` endpoint which we can use to find proper names for our agencies
- [ ] It should accept a single request with 
   -  `external name` 
   -  `county`
   -  `state`
   - `locality`
- [ ] It should return 
   -  `agency name`: great for CSV submissions
   -  `agency id`: good for hitting the API
- [ ] It should return one of 3 possible entries:
   - `exact match`, if one confident match is detected; this covers the `happy` and `different` paths
   - `possible match`, an exact match is not found, but there are one or more agencies within the same location which might match
   - `no match`, No agencies found for that location and/or meet the threshold for being a possible match.
- [x] Determine if this should be an endpoint vs. an internal tool used by the scrapers. For example, a read-only SQLite database of agencies (which could minimize endpoint calls).
  - determined that this should be an endpoint because of the broad usage
- [ ] Agencies may have the same name across different states or counties. we should disambiguate using counties or states.
<img width="258" alt="Screen Shot 2024-11-13 at 12 21 19 PM" src="https://github.com/user-attachments/assets/a6e83798-26dd-40e1-bdb5-af13601d4363">

### How would we do this internally?

We have several possible ways of approaching this, depending on our preferences and how thorough we want to be. This includes:
* Exact matching -- Probably will do this regardless as a means of first-past-the-post checking
* Fuzzy string matching -- things like [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance), [Jaro-Winkler similarity](https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance), or [Cosine similarity](https://en.wikipedia.org/wiki/Cosine_similarity)
* [Phonetic matching](https://en.wikipedia.org/wiki/Phonetic_algorithm)
* [N-gram matching](https://en.wikipedia.org/wiki/N-gram)
* Machine learning-based solutions

**Comment by maxachis** [comment]
Looking at this now!

@josh-chamberlain When we say it should accept a batch, are we thinking of providing that batch via csv, json, or both?

**Comment by maxachis** [comment]
In terms of implementation, here's my initial thinking: 

## Steps
1.	Get all agencies whose location id match the location id that is derived from the state/county/locality
  a.	This assumes exact matching. 
2.	Of values retrieved, perform fuzzy matching on names. Exact matches are labeled as such, while possible matches (i.e. those where the similarity is above some threshold) are included. Anything below the threshold is not returned. 

## Possible Outcomes
A.	Exact match
B.	Possible matches
C.	No matches but other agencies with that location
D.	No agencies with that location. 

## Other Considerations
* This will be premised on locations being exactly correct. Misspellings or alternative names (e.g., "St." instead of "Saint") won't be considered.
