### ISSUE TITLE
Look into location filtering for `/data-requests`

### ISSUE THREAD

**Issue by joshuagraber** [Police-Data-Accessibility-Project/data-sources-app#561]
### Context

Background: in the web app, we're fetching requests associated with a search. Location filtering would be desirable so as not to return the entire array of requests in each network call.

### Requirements

- Do we want to pass a list of location ids as a param? 
pros: would allow filtering multiple locations.
cons: would require request orchestration on the client.
- Or add a new endpoint `/data-requests/<location_id>`
pros: stable, we'll have the location id data and can pass it immediately without waiting for other requests to return.
const: single location (although that's all we really need right now)
- Or add associated requests to the `/search/search-location-and-record-type` endpoint.
pros: one request on the client search route.
cons: data coupling where it's not strictly necessary

### Tests

- tests to cover any changes

### Docs

- docs to cover any changes

### Open questions

What strategy we want to use.

**Comment by maxachis** [comment]
> Or add a new endpoint /data-requests/<location_id>
pros: stable, we'll have the location id data and can pass it immediately without waiting for other requests to return.
const: single location (although that's all we really need right now)

How about: `/locations/{location_id}/data-requests`? This way, we'd not only be able to get data requests associated with a location, but potentially other things, such as agencies, in the future. Also opens the door for more fine manipulations of location information if we need to (for example: adding, updating, or removing locations).

**Comment by joshuagraber** [comment]
> How about: /locations/{location_id}/data-requests?

Even better, @maxachis. Could we also add a `GET` to `/locations/{location_id}`? Since we're now matching locations based on id, being able to make a simple get by ID req would allow for a bit of simplification on the client.

**Comment by maxachis** [comment]
> > How about: /locations/{location_id}/data-requests?
> 
> Even better, @maxachis. Could we also add a `GET` to `/locations/{location_id}`? Since we're now matching locations based on id, being able to make a simple get by ID req would allow for a bit of simplification on the client.

@joshuagraber DONE
