### ISSUE TITLE
default values for some properties

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#70]
### Context

We have a lot of null values in the database. Airtable doesn't seamlessly allow `default` values, but SQL does.

### Requirements

- [x] when new rows are added with null values (from airtable or otherwise), these defaults should take over

property | default value | note
--- | --- | ---
approved | false | 
url_status | ok | 
data_source_created | `now` | this is handled in Airtable, but soon we will be creating them outside Airtable

I, uh, thought there would be more of these when I started making the issue.

### Docs

- [x] update the [data dictionary](https://docs.pdap.io/activities/data-sources/data-dictionaries/data-sources-data-dictionary) with a `default` column

**Comment by kalenluciano** [comment]
I updated the docs and made the changes in the code in [this issue](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/153)
