### ISSUE TITLE
data sources monthly digest email

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#75]
### Context
We have mailgun set up for the password reset workflow. We should use that to make a monthly email to anyone who chooses to subscribe. The logic should be to use all data sources from the API that are edited within the last month, but in the future we will have parameters—for example, people can subscribe to updates _for a specific search_ of data sources.

## Requirements
- requires https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/419
- [ ] get an API key from PDAP
- [ ] create a script which hits our API and sends a Mailgun email with the below contents
- [ ] test the script with your own Mailgun API key (free)
   - when you submit, include the test results
- [ ] PDAP staff will set up the automation with Jenkins, our pipeline
- [ ] The script should use environment variables: `SECRET_KEY` for the API key and `MAILGUN_KEY` for Mailgun.

### Email Contents
>New data sources: `number of rows`
>Updates to existing sources: `number of rows`
>Number of agencies affected by new/updated sources: `number of agencies`
>Explore the data at https://pdap.io/data

### Email Recipients
`operations@pdap.io`

### Email Frequency
Monthly, on the first at 12pm (noon) ET.

**Comment by josh-chamberlain** [comment]
Hi there @aaryauchamkeri ! Yes, that would be much appreciated. I tweaked the issue to contain more detail and I'm going to cc @maxachis to answer a couple questions:

- I'm thinking the v2 API is ready for this, because the needs are basic; it might save some effort later. Would you agree?
  - based on the answer to this, could you please create an account so our fine volunteer has an API key? I don't think we have self-serve signup live anywhere yet.
- Can this live in the main app repo? If so, where should it go? I assume since it's so small that's simplest.

**Comment by maxachis** [comment]
@josh-chamberlain @aaryauchamkeri 

Yes, I believe this can get started now! There are a few components to this as I envision it:

- [ ] Either adding a new endpoint to get information on new and updated data sources, or tweaking the `data-sources` endpoint to be able to get the requisite information on desired filters.
- [ ] Developing an automated script which calls that endpoint and then performs the requisite mailgun wizardry (this I believe is where @aaryauchamkeri can come in most readily)
- [ ] Putting together the Jenkins components along with a list of subscribers.

@aaryauchamkeri and I can chit-chat in discord about setting them up with an API key (I can be found as PDAP Staff with a fun little goose as my profile picture).

**Comment by maxachis** [comment]
@josh-chamberlain Now that we have it so that people can, in fact, subscribe to specific searches, is this issue still germane?

**Comment by josh-chamberlain** [comment]
@maxachis hey, we skipped the MVP! nice.
