### ISSUE TITLE
Fix bug to allow refresh on quick search results and data source static view

### ISSUE THREAD

**Issue by kalenluciano** [Police-Data-Accessibility-Project/data-sources-app#81]
### Context

Refreshing the live site (https://data-sources.pdap.io/) on any page besides for the home page causes the app to show a 404 error page. Users should be able to refresh their results or data source static view page and the content should persist. This wasn't an issue happening locally in development, so it may be related to deployment. This also might help with sharing links to search results.

### Requirements

* Make website content persist/prevent 404 error on a refresh

**Comment by josh-chamberlain** [comment]
Example: this was generated by a search from another user, but when the link was shared with me, I got a 404. I could go make the search myself and get the results.

https://data-sources.pdap.io/search/Officer%20Involved%20Shootings/detroit

this is (maybe) a heavier lift, but needs to happen anyway and will achieve the desired effect by creating permalinks to searches. consider doing it instead: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/21

**Comment by kalenluciano** [comment]
As @josh-chamberlain mentioned [here](https://github.com/Police-Data-Accessibility-Project/pdap.io/pull/141#issuecomment-1789575204), I was able to fix this bug by adding a "custom catchall page"
