### ISSUE TITLE
implement design system in data-sources-app

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#85]
### Context: 
Once the design system is ready for it, we should start using it in the app before we make any other big decisions about navigation and CTAs.

### Requirements
- [ ] use the README in the design-system repo for instructions

**Comment by joshuagraber** [comment]
@josh-chamberlain No, I don't think so. If I do my job with the `design-system` docs, it should be pretty self-explanatory.

**Comment by joshuagraber** [comment]
Re-opening, as this is not actually complete:

We need to bump to `v2.0.1` in order to have the `QuickSearchForm` component here as well.

**Comment by josh-chamberlain** [comment]
fixed in https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/143
