### ISSUE TITLE
quick search: Support full state string search

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-sources-app#93]
### Context

This is not the most urgent, but makes an impact on user experience.

              @josh-chamberlain On the state, currently searches won't return for a full state string because we aren't currently storing it in any of the tables.

_Originally posted by @mbodeantor in https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/91#issuecomment-1802204773_
            
### Requirements
- [ ] as a quick search user, typing "Pennsylvania" in "where" should work as well as "PA".
   (is the idea to make a table of states? handle the conversion in the back end?)

**Comment by mbodeantor** [comment]
Yeah I think easiest would be just a two column table with abbreviation and full name which the back end can join to in queries for agencies
